// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumiverse.exoscale.inputs.ComputeInstanceNetworkInterfaceArgs;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ComputeInstanceArgs extends com.pulumi.resources.ResourceArgs {

    public static final ComputeInstanceArgs Empty = new ComputeInstanceArgs();

    /**
     * A list of exoscale.AntiAffinityGroup (IDs) to attach to the instance (may only be set at creation time).
     * 
     */
    @Import(name="antiAffinityGroupIds")
    private @Nullable Output<List<String>> antiAffinityGroupIds;

    /**
     * @return A list of exoscale.AntiAffinityGroup (IDs) to attach to the instance (may only be set at creation time).
     * 
     */
    public Optional<Output<List<String>>> antiAffinityGroupIds() {
        return Optional.ofNullable(this.antiAffinityGroupIds);
    }

    /**
     * A deploy target ID.
     * 
     */
    @Import(name="deployTargetId")
    private @Nullable Output<String> deployTargetId;

    /**
     * @return A deploy target ID.
     * 
     */
    public Optional<Output<String>> deployTargetId() {
        return Optional.ofNullable(this.deployTargetId);
    }

    /**
     * The instance disk size (GiB; at least `10`). **WARNING**: updating this attribute stops/restarts the instance.
     * 
     */
    @Import(name="diskSize")
    private @Nullable Output<Integer> diskSize;

    /**
     * @return The instance disk size (GiB; at least `10`). **WARNING**: updating this attribute stops/restarts the instance.
     * 
     */
    public Optional<Output<Integer>> diskSize() {
        return Optional.ofNullable(this.diskSize);
    }

    /**
     * A list of exoscale.ElasticIP (IDs) to attach to the instance.
     * 
     */
    @Import(name="elasticIpIds")
    private @Nullable Output<List<String>> elasticIpIds;

    /**
     * @return A list of exoscale.ElasticIP (IDs) to attach to the instance.
     * 
     */
    public Optional<Output<List<String>>> elasticIpIds() {
        return Optional.ofNullable(this.elasticIpIds);
    }

    /**
     * Enable IPv6 on the instance (boolean; default: `false`).
     * 
     */
    @Import(name="ipv6")
    private @Nullable Output<Boolean> ipv6;

    /**
     * @return Enable IPv6 on the instance (boolean; default: `false`).
     * 
     */
    public Optional<Output<Boolean>> ipv6() {
        return Optional.ofNullable(this.ipv6);
    }

    /**
     * A map of key/value labels.
     * 
     */
    @Import(name="labels")
    private @Nullable Output<Map<String,String>> labels;

    /**
     * @return A map of key/value labels.
     * 
     */
    public Optional<Output<Map<String,String>>> labels() {
        return Optional.ofNullable(this.labels);
    }

    /**
     * The compute instance name.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The compute instance name.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Private network interfaces (may be specified multiple times). Structure is documented below.
     * 
     */
    @Import(name="networkInterfaces")
    private @Nullable Output<List<ComputeInstanceNetworkInterfaceArgs>> networkInterfaces;

    /**
     * @return Private network interfaces (may be specified multiple times). Structure is documented below.
     * 
     */
    public Optional<Output<List<ComputeInstanceNetworkInterfaceArgs>>> networkInterfaces() {
        return Optional.ofNullable(this.networkInterfaces);
    }

    /**
     * A list of exoscale.SecurityGroup (IDs) to attach to the instance.
     * 
     */
    @Import(name="securityGroupIds")
    private @Nullable Output<List<String>> securityGroupIds;

    /**
     * @return A list of exoscale.SecurityGroup (IDs) to attach to the instance.
     * 
     */
    public Optional<Output<List<String>>> securityGroupIds() {
        return Optional.ofNullable(this.securityGroupIds);
    }

    /**
     * The exoscale.SSHKey (name) to authorize in the instance (may only be set at creation time).
     * 
     */
    @Import(name="sshKey")
    private @Nullable Output<String> sshKey;

    /**
     * @return The exoscale.SSHKey (name) to authorize in the instance (may only be set at creation time).
     * 
     */
    public Optional<Output<String>> sshKey() {
        return Optional.ofNullable(this.sshKey);
    }

    /**
     * The instance state (`running` or `stopped`; default: `running`).
     * 
     */
    @Import(name="state")
    private @Nullable Output<String> state;

    /**
     * @return The instance state (`running` or `stopped`; default: `running`).
     * 
     */
    public Optional<Output<String>> state() {
        return Optional.ofNullable(this.state);
    }

    /**
     * The exoscale.getComputeTemplate (ID) to use when creating the instance.
     * 
     */
    @Import(name="templateId", required=true)
    private Output<String> templateId;

    /**
     * @return The exoscale.getComputeTemplate (ID) to use when creating the instance.
     * 
     */
    public Output<String> templateId() {
        return this.templateId;
    }

    /**
     * The instance type (`&lt;family&gt;.&lt;size&gt;`, e.g. `standard.medium`; use the [Exoscale CLI][cli] - `exo compute instance-type list` - for the list of available types). **WARNING**: updating this attribute stops/restarts the instance.
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return The instance type (`&lt;family&gt;.&lt;size&gt;`, e.g. `standard.medium`; use the [Exoscale CLI][cli] - `exo compute instance-type list` - for the list of available types). **WARNING**: updating this attribute stops/restarts the instance.
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    /**
     * [cloud-init][cloud-init] configuration (no need to base64-encode or gzip it as the provider will take care of it).
     * 
     */
    @Import(name="userData")
    private @Nullable Output<String> userData;

    /**
     * @return [cloud-init][cloud-init] configuration (no need to base64-encode or gzip it as the provider will take care of it).
     * 
     */
    public Optional<Output<String>> userData() {
        return Optional.ofNullable(this.userData);
    }

    /**
     * The Exoscale [Zone][zone] name.
     * 
     */
    @Import(name="zone", required=true)
    private Output<String> zone;

    /**
     * @return The Exoscale [Zone][zone] name.
     * 
     */
    public Output<String> zone() {
        return this.zone;
    }

    private ComputeInstanceArgs() {}

    private ComputeInstanceArgs(ComputeInstanceArgs $) {
        this.antiAffinityGroupIds = $.antiAffinityGroupIds;
        this.deployTargetId = $.deployTargetId;
        this.diskSize = $.diskSize;
        this.elasticIpIds = $.elasticIpIds;
        this.ipv6 = $.ipv6;
        this.labels = $.labels;
        this.name = $.name;
        this.networkInterfaces = $.networkInterfaces;
        this.securityGroupIds = $.securityGroupIds;
        this.sshKey = $.sshKey;
        this.state = $.state;
        this.templateId = $.templateId;
        this.type = $.type;
        this.userData = $.userData;
        this.zone = $.zone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ComputeInstanceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ComputeInstanceArgs $;

        public Builder() {
            $ = new ComputeInstanceArgs();
        }

        public Builder(ComputeInstanceArgs defaults) {
            $ = new ComputeInstanceArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param antiAffinityGroupIds A list of exoscale.AntiAffinityGroup (IDs) to attach to the instance (may only be set at creation time).
         * 
         * @return builder
         * 
         */
        public Builder antiAffinityGroupIds(@Nullable Output<List<String>> antiAffinityGroupIds) {
            $.antiAffinityGroupIds = antiAffinityGroupIds;
            return this;
        }

        /**
         * @param antiAffinityGroupIds A list of exoscale.AntiAffinityGroup (IDs) to attach to the instance (may only be set at creation time).
         * 
         * @return builder
         * 
         */
        public Builder antiAffinityGroupIds(List<String> antiAffinityGroupIds) {
            return antiAffinityGroupIds(Output.of(antiAffinityGroupIds));
        }

        /**
         * @param antiAffinityGroupIds A list of exoscale.AntiAffinityGroup (IDs) to attach to the instance (may only be set at creation time).
         * 
         * @return builder
         * 
         */
        public Builder antiAffinityGroupIds(String... antiAffinityGroupIds) {
            return antiAffinityGroupIds(List.of(antiAffinityGroupIds));
        }

        /**
         * @param deployTargetId A deploy target ID.
         * 
         * @return builder
         * 
         */
        public Builder deployTargetId(@Nullable Output<String> deployTargetId) {
            $.deployTargetId = deployTargetId;
            return this;
        }

        /**
         * @param deployTargetId A deploy target ID.
         * 
         * @return builder
         * 
         */
        public Builder deployTargetId(String deployTargetId) {
            return deployTargetId(Output.of(deployTargetId));
        }

        /**
         * @param diskSize The instance disk size (GiB; at least `10`). **WARNING**: updating this attribute stops/restarts the instance.
         * 
         * @return builder
         * 
         */
        public Builder diskSize(@Nullable Output<Integer> diskSize) {
            $.diskSize = diskSize;
            return this;
        }

        /**
         * @param diskSize The instance disk size (GiB; at least `10`). **WARNING**: updating this attribute stops/restarts the instance.
         * 
         * @return builder
         * 
         */
        public Builder diskSize(Integer diskSize) {
            return diskSize(Output.of(diskSize));
        }

        /**
         * @param elasticIpIds A list of exoscale.ElasticIP (IDs) to attach to the instance.
         * 
         * @return builder
         * 
         */
        public Builder elasticIpIds(@Nullable Output<List<String>> elasticIpIds) {
            $.elasticIpIds = elasticIpIds;
            return this;
        }

        /**
         * @param elasticIpIds A list of exoscale.ElasticIP (IDs) to attach to the instance.
         * 
         * @return builder
         * 
         */
        public Builder elasticIpIds(List<String> elasticIpIds) {
            return elasticIpIds(Output.of(elasticIpIds));
        }

        /**
         * @param elasticIpIds A list of exoscale.ElasticIP (IDs) to attach to the instance.
         * 
         * @return builder
         * 
         */
        public Builder elasticIpIds(String... elasticIpIds) {
            return elasticIpIds(List.of(elasticIpIds));
        }

        /**
         * @param ipv6 Enable IPv6 on the instance (boolean; default: `false`).
         * 
         * @return builder
         * 
         */
        public Builder ipv6(@Nullable Output<Boolean> ipv6) {
            $.ipv6 = ipv6;
            return this;
        }

        /**
         * @param ipv6 Enable IPv6 on the instance (boolean; default: `false`).
         * 
         * @return builder
         * 
         */
        public Builder ipv6(Boolean ipv6) {
            return ipv6(Output.of(ipv6));
        }

        /**
         * @param labels A map of key/value labels.
         * 
         * @return builder
         * 
         */
        public Builder labels(@Nullable Output<Map<String,String>> labels) {
            $.labels = labels;
            return this;
        }

        /**
         * @param labels A map of key/value labels.
         * 
         * @return builder
         * 
         */
        public Builder labels(Map<String,String> labels) {
            return labels(Output.of(labels));
        }

        /**
         * @param name The compute instance name.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The compute instance name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param networkInterfaces Private network interfaces (may be specified multiple times). Structure is documented below.
         * 
         * @return builder
         * 
         */
        public Builder networkInterfaces(@Nullable Output<List<ComputeInstanceNetworkInterfaceArgs>> networkInterfaces) {
            $.networkInterfaces = networkInterfaces;
            return this;
        }

        /**
         * @param networkInterfaces Private network interfaces (may be specified multiple times). Structure is documented below.
         * 
         * @return builder
         * 
         */
        public Builder networkInterfaces(List<ComputeInstanceNetworkInterfaceArgs> networkInterfaces) {
            return networkInterfaces(Output.of(networkInterfaces));
        }

        /**
         * @param networkInterfaces Private network interfaces (may be specified multiple times). Structure is documented below.
         * 
         * @return builder
         * 
         */
        public Builder networkInterfaces(ComputeInstanceNetworkInterfaceArgs... networkInterfaces) {
            return networkInterfaces(List.of(networkInterfaces));
        }

        /**
         * @param securityGroupIds A list of exoscale.SecurityGroup (IDs) to attach to the instance.
         * 
         * @return builder
         * 
         */
        public Builder securityGroupIds(@Nullable Output<List<String>> securityGroupIds) {
            $.securityGroupIds = securityGroupIds;
            return this;
        }

        /**
         * @param securityGroupIds A list of exoscale.SecurityGroup (IDs) to attach to the instance.
         * 
         * @return builder
         * 
         */
        public Builder securityGroupIds(List<String> securityGroupIds) {
            return securityGroupIds(Output.of(securityGroupIds));
        }

        /**
         * @param securityGroupIds A list of exoscale.SecurityGroup (IDs) to attach to the instance.
         * 
         * @return builder
         * 
         */
        public Builder securityGroupIds(String... securityGroupIds) {
            return securityGroupIds(List.of(securityGroupIds));
        }

        /**
         * @param sshKey The exoscale.SSHKey (name) to authorize in the instance (may only be set at creation time).
         * 
         * @return builder
         * 
         */
        public Builder sshKey(@Nullable Output<String> sshKey) {
            $.sshKey = sshKey;
            return this;
        }

        /**
         * @param sshKey The exoscale.SSHKey (name) to authorize in the instance (may only be set at creation time).
         * 
         * @return builder
         * 
         */
        public Builder sshKey(String sshKey) {
            return sshKey(Output.of(sshKey));
        }

        /**
         * @param state The instance state (`running` or `stopped`; default: `running`).
         * 
         * @return builder
         * 
         */
        public Builder state(@Nullable Output<String> state) {
            $.state = state;
            return this;
        }

        /**
         * @param state The instance state (`running` or `stopped`; default: `running`).
         * 
         * @return builder
         * 
         */
        public Builder state(String state) {
            return state(Output.of(state));
        }

        /**
         * @param templateId The exoscale.getComputeTemplate (ID) to use when creating the instance.
         * 
         * @return builder
         * 
         */
        public Builder templateId(Output<String> templateId) {
            $.templateId = templateId;
            return this;
        }

        /**
         * @param templateId The exoscale.getComputeTemplate (ID) to use when creating the instance.
         * 
         * @return builder
         * 
         */
        public Builder templateId(String templateId) {
            return templateId(Output.of(templateId));
        }

        /**
         * @param type The instance type (`&lt;family&gt;.&lt;size&gt;`, e.g. `standard.medium`; use the [Exoscale CLI][cli] - `exo compute instance-type list` - for the list of available types). **WARNING**: updating this attribute stops/restarts the instance.
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type The instance type (`&lt;family&gt;.&lt;size&gt;`, e.g. `standard.medium`; use the [Exoscale CLI][cli] - `exo compute instance-type list` - for the list of available types). **WARNING**: updating this attribute stops/restarts the instance.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        /**
         * @param userData [cloud-init][cloud-init] configuration (no need to base64-encode or gzip it as the provider will take care of it).
         * 
         * @return builder
         * 
         */
        public Builder userData(@Nullable Output<String> userData) {
            $.userData = userData;
            return this;
        }

        /**
         * @param userData [cloud-init][cloud-init] configuration (no need to base64-encode or gzip it as the provider will take care of it).
         * 
         * @return builder
         * 
         */
        public Builder userData(String userData) {
            return userData(Output.of(userData));
        }

        /**
         * @param zone The Exoscale [Zone][zone] name.
         * 
         * @return builder
         * 
         */
        public Builder zone(Output<String> zone) {
            $.zone = zone;
            return this;
        }

        /**
         * @param zone The Exoscale [Zone][zone] name.
         * 
         * @return builder
         * 
         */
        public Builder zone(String zone) {
            return zone(Output.of(zone));
        }

        public ComputeInstanceArgs build() {
            $.templateId = Objects.requireNonNull($.templateId, "expected parameter 'templateId' to be non-null");
            $.type = Objects.requireNonNull($.type, "expected parameter 'type' to be non-null");
            $.zone = Objects.requireNonNull($.zone, "expected parameter 'zone' to be non-null");
            return $;
        }
    }

}
