// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumiverse.exoscale.ElasticIPArgs;
import com.pulumiverse.exoscale.Utilities;
import com.pulumiverse.exoscale.inputs.ElasticIPState;
import com.pulumiverse.exoscale.outputs.ElasticIPHealthcheck;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * Manage Exoscale [Elastic IPs (EIP)](https://community.exoscale.com/documentation/compute/eip/).
 * 
 * Corresponding data source: exoscale_elastic_ip.
 * 
 * ## Import
 * 
 * An existing Elastic IP (EIP) may be imported by `&lt;ID&gt;@&lt;zone&gt;`console
 * 
 * ```sh
 *  $ pulumi import exoscale:index/elasticIP:ElasticIP \
 * ```
 * 
 *  exoscale_elastic_ip.my_elastic_ip \
 * 
 *  f81d4fae-7dec-11d0-a765-00a0c91e6bf6@ch-gva-2
 * 
 */
@ResourceType(type="exoscale:index/elasticIP:ElasticIP")
public class ElasticIP extends com.pulumi.resources.CustomResource {
    /**
     * The Elastic IP (EIP) address family (`inet4` or `inet6`; default: `inet4`).
     * 
     */
    @Export(name="addressFamily", type=String.class, parameters={})
    private Output<String> addressFamily;

    /**
     * @return The Elastic IP (EIP) address family (`inet4` or `inet6`; default: `inet4`).
     * 
     */
    public Output<String> addressFamily() {
        return this.addressFamily;
    }
    /**
     * The Elastic IP (EIP) CIDR.
     * 
     */
    @Export(name="cidr", type=String.class, parameters={})
    private Output<String> cidr;

    /**
     * @return The Elastic IP (EIP) CIDR.
     * 
     */
    public Output<String> cidr() {
        return this.cidr;
    }
    /**
     * A free-form text describing the Elastic IP (EIP).
     * 
     */
    @Export(name="description", type=String.class, parameters={})
    private Output<String> description;

    /**
     * @return A free-form text describing the Elastic IP (EIP).
     * 
     */
    public Output<String> description() {
        return this.description;
    }
    /**
     * Healthcheck configuration for *managed* EIPs. Structure is documented below.
     * 
     */
    @Export(name="healthcheck", type=ElasticIPHealthcheck.class, parameters={})
    private Output<ElasticIPHealthcheck> healthcheck;

    /**
     * @return Healthcheck configuration for *managed* EIPs. Structure is documented below.
     * 
     */
    public Output<ElasticIPHealthcheck> healthcheck() {
        return this.healthcheck;
    }
    /**
     * The Elastic IP (EIP) IPv4 or IPv6 address.
     * 
     */
    @Export(name="ipAddress", type=String.class, parameters={})
    private Output<String> ipAddress;

    /**
     * @return The Elastic IP (EIP) IPv4 or IPv6 address.
     * 
     */
    public Output<String> ipAddress() {
        return this.ipAddress;
    }
    /**
     * The Exoscale [Zone][zone] name.
     * 
     */
    @Export(name="zone", type=String.class, parameters={})
    private Output<String> zone;

    /**
     * @return The Exoscale [Zone][zone] name.
     * 
     */
    public Output<String> zone() {
        return this.zone;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ElasticIP(String name) {
        this(name, ElasticIPArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ElasticIP(String name, ElasticIPArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ElasticIP(String name, ElasticIPArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("exoscale:index/elasticIP:ElasticIP", name, args == null ? ElasticIPArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private ElasticIP(String name, Output<String> id, @Nullable ElasticIPState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("exoscale:index/elasticIP:ElasticIP", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ElasticIP get(String name, Output<String> id, @Nullable ElasticIPState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ElasticIP(name, id, state, options);
    }
}
