// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumiverse.exoscale.NICArgs;
import com.pulumiverse.exoscale.Utilities;
import com.pulumiverse.exoscale.inputs.NICState;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * !&gt; **WARNING:** This resource is **DEPRECATED** and will be removed in the next major version. Please use exoscale.ComputeInstance `network_interface` block instead.
 * 
 */
@ResourceType(type="exoscale:index/nIC:NIC")
public class NIC extends com.pulumi.resources.CustomResource {
    /**
     * The compute instance ID.
     * 
     */
    @Export(name="computeId", type=String.class, parameters={})
    private Output<String> computeId;

    /**
     * @return The compute instance ID.
     * 
     */
    public Output<String> computeId() {
        return this.computeId;
    }
    @Export(name="gateway", type=String.class, parameters={})
    private Output<String> gateway;

    public Output<String> gateway() {
        return this.gateway;
    }
    /**
     * The IPv4 address to request as static DHCP lease if the NIC is attached to a *managed* private network.
     * 
     */
    @Export(name="ipAddress", type=String.class, parameters={})
    private Output<String> ipAddress;

    /**
     * @return The IPv4 address to request as static DHCP lease if the NIC is attached to a *managed* private network.
     * 
     */
    public Output<String> ipAddress() {
        return this.ipAddress;
    }
    /**
     * The NIC MAC address.
     * 
     */
    @Export(name="macAddress", type=String.class, parameters={})
    private Output<String> macAddress;

    /**
     * @return The NIC MAC address.
     * 
     */
    public Output<String> macAddress() {
        return this.macAddress;
    }
    @Export(name="netmask", type=String.class, parameters={})
    private Output<String> netmask;

    public Output<String> netmask() {
        return this.netmask;
    }
    /**
     * The private network ID.
     * 
     */
    @Export(name="networkId", type=String.class, parameters={})
    private Output<String> networkId;

    /**
     * @return The private network ID.
     * 
     */
    public Output<String> networkId() {
        return this.networkId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public NIC(String name) {
        this(name, NICArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public NIC(String name, NICArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public NIC(String name, NICArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("exoscale:index/nIC:NIC", name, args == null ? NICArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private NIC(String name, Output<String> id, @Nullable NICState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("exoscale:index/nIC:NIC", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static NIC get(String name, Output<String> id, @Nullable NICState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new NIC(name, id, state, options);
    }
}
