// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumiverse.exoscale.NLBArgs;
import com.pulumiverse.exoscale.Utilities;
import com.pulumiverse.exoscale.inputs.NLBState;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ## Import
 * 
 * An existing network load balancer (NLB) may be imported by `&lt;ID&gt;@&lt;zone&gt;`console
 * 
 * ```sh
 *  $ pulumi import exoscale:index/nLB:NLB \
 * ```
 * 
 *  exoscale_nlb.my_nlb \
 * 
 *  f81d4fae-7dec-11d0-a765-00a0c91e6bf6@ch-gva-2
 * 
 */
@ResourceType(type="exoscale:index/nLB:NLB")
public class NLB extends com.pulumi.resources.CustomResource {
    /**
     * The NLB creation date.
     * 
     */
    @Export(name="createdAt", type=String.class, parameters={})
    private Output<String> createdAt;

    /**
     * @return The NLB creation date.
     * 
     */
    public Output<String> createdAt() {
        return this.createdAt;
    }
    /**
     * A free-form text describing the NLB.
     * 
     */
    @Export(name="description", type=String.class, parameters={})
    private Output</* @Nullable */ String> description;

    /**
     * @return A free-form text describing the NLB.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * The NLB IPv4 address.
     * 
     */
    @Export(name="ipAddress", type=String.class, parameters={})
    private Output<String> ipAddress;

    /**
     * @return The NLB IPv4 address.
     * 
     */
    public Output<String> ipAddress() {
        return this.ipAddress;
    }
    /**
     * A map of key/value labels.
     * 
     */
    @Export(name="labels", type=Map.class, parameters={String.class, String.class})
    private Output</* @Nullable */ Map<String,String>> labels;

    /**
     * @return A map of key/value labels.
     * 
     */
    public Output<Optional<Map<String,String>>> labels() {
        return Codegen.optional(this.labels);
    }
    /**
     * The network load balancer (NLB) name.
     * 
     */
    @Export(name="name", type=String.class, parameters={})
    private Output<String> name;

    /**
     * @return The network load balancer (NLB) name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The list of the exoscale.NLBService (names).
     * 
     */
    @Export(name="services", type=List.class, parameters={String.class})
    private Output<List<String>> services;

    /**
     * @return The list of the exoscale.NLBService (names).
     * 
     */
    public Output<List<String>> services() {
        return this.services;
    }
    /**
     * The current NLB state.
     * 
     */
    @Export(name="state", type=String.class, parameters={})
    private Output<String> state;

    /**
     * @return The current NLB state.
     * 
     */
    public Output<String> state() {
        return this.state;
    }
    /**
     * The Exoscale [Zone][zone] name.
     * 
     */
    @Export(name="zone", type=String.class, parameters={})
    private Output<String> zone;

    /**
     * @return The Exoscale [Zone][zone] name.
     * 
     */
    public Output<String> zone() {
        return this.zone;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public NLB(String name) {
        this(name, NLBArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public NLB(String name, NLBArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public NLB(String name, NLBArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("exoscale:index/nLB:NLB", name, args == null ? NLBArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private NLB(String name, Output<String> id, @Nullable NLBState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("exoscale:index/nLB:NLB", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static NLB get(String name, Output<String> id, @Nullable NLBState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new NLB(name, id, state, options);
    }
}
