// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumiverse.exoscale.ProviderArgs;
import com.pulumiverse.exoscale.Utilities;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * The provider type for the exoscale package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 * 
 */
@ResourceType(type="pulumi:providers:exoscale")
public class Provider extends com.pulumi.resources.ProviderResource {
    /**
     * Exoscale CloudStack API endpoint (by default: https://api.exoscale.com/v1)
     * 
     */
    @Export(name="computeEndpoint", type=String.class, parameters={})
    private Output</* @Nullable */ String> computeEndpoint;

    /**
     * @return Exoscale CloudStack API endpoint (by default: https://api.exoscale.com/v1)
     * 
     */
    public Output<Optional<String>> computeEndpoint() {
        return Codegen.optional(this.computeEndpoint);
    }
    /**
     * CloudStack ini configuration filename (by default: cloudstack.ini)
     * 
     */
    @Export(name="config", type=String.class, parameters={})
    private Output</* @Nullable */ String> config;

    /**
     * @return CloudStack ini configuration filename (by default: cloudstack.ini)
     * 
     */
    public Output<Optional<String>> config() {
        return Codegen.optional(this.config);
    }
    /**
     * Exoscale DNS API endpoint (by default: https://api.exoscale.com/dns)
     * 
     */
    @Export(name="dnsEndpoint", type=String.class, parameters={})
    private Output<String> dnsEndpoint;

    /**
     * @return Exoscale DNS API endpoint (by default: https://api.exoscale.com/dns)
     * 
     */
    public Output<String> dnsEndpoint() {
        return this.dnsEndpoint;
    }
    @Export(name="environment", type=String.class, parameters={})
    private Output</* @Nullable */ String> environment;

    public Output<Optional<String>> environment() {
        return Codegen.optional(this.environment);
    }
    /**
     * Exoscale API key
     * 
     */
    @Export(name="key", type=String.class, parameters={})
    private Output</* @Nullable */ String> key;

    /**
     * @return Exoscale API key
     * 
     */
    public Output<Optional<String>> key() {
        return Codegen.optional(this.key);
    }
    /**
     * @deprecated
     * Use region instead
     * 
     */
    @Deprecated /* Use region instead */
    @Export(name="profile", type=String.class, parameters={})
    private Output</* @Nullable */ String> profile;

    public Output<Optional<String>> profile() {
        return Codegen.optional(this.profile);
    }
    /**
     * CloudStack ini configuration section name (by default: cloudstack)
     * 
     */
    @Export(name="region", type=String.class, parameters={})
    private Output</* @Nullable */ String> region;

    /**
     * @return CloudStack ini configuration section name (by default: cloudstack)
     * 
     */
    public Output<Optional<String>> region() {
        return Codegen.optional(this.region);
    }
    /**
     * Exoscale API secret
     * 
     */
    @Export(name="secret", type=String.class, parameters={})
    private Output</* @Nullable */ String> secret;

    /**
     * @return Exoscale API secret
     * 
     */
    public Output<Optional<String>> secret() {
        return Codegen.optional(this.secret);
    }
    /**
     * @deprecated
     * Use key instead
     * 
     */
    @Deprecated /* Use key instead */
    @Export(name="token", type=String.class, parameters={})
    private Output</* @Nullable */ String> token;

    public Output<Optional<String>> token() {
        return Codegen.optional(this.token);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Provider(String name) {
        this(name, ProviderArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Provider(String name, ProviderArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Provider(String name, ProviderArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("exoscale", name, args == null ? ProviderArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "secret"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

}
