// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class SecondaryIPAddressArgs extends com.pulumi.resources.ResourceArgs {

    public static final SecondaryIPAddressArgs Empty = new SecondaryIPAddressArgs();

    /**
     * The compute instance ID.
     * 
     */
    @Import(name="computeId", required=true)
    private Output<String> computeId;

    /**
     * @return The compute instance ID.
     * 
     */
    public Output<String> computeId() {
        return this.computeId;
    }

    /**
     * The Elastic IP (EIP) address.
     * 
     */
    @Import(name="ipAddress", required=true)
    private Output<String> ipAddress;

    /**
     * @return The Elastic IP (EIP) address.
     * 
     */
    public Output<String> ipAddress() {
        return this.ipAddress;
    }

    private SecondaryIPAddressArgs() {}

    private SecondaryIPAddressArgs(SecondaryIPAddressArgs $) {
        this.computeId = $.computeId;
        this.ipAddress = $.ipAddress;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SecondaryIPAddressArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SecondaryIPAddressArgs $;

        public Builder() {
            $ = new SecondaryIPAddressArgs();
        }

        public Builder(SecondaryIPAddressArgs defaults) {
            $ = new SecondaryIPAddressArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param computeId The compute instance ID.
         * 
         * @return builder
         * 
         */
        public Builder computeId(Output<String> computeId) {
            $.computeId = computeId;
            return this;
        }

        /**
         * @param computeId The compute instance ID.
         * 
         * @return builder
         * 
         */
        public Builder computeId(String computeId) {
            return computeId(Output.of(computeId));
        }

        /**
         * @param ipAddress The Elastic IP (EIP) address.
         * 
         * @return builder
         * 
         */
        public Builder ipAddress(Output<String> ipAddress) {
            $.ipAddress = ipAddress;
            return this;
        }

        /**
         * @param ipAddress The Elastic IP (EIP) address.
         * 
         * @return builder
         * 
         */
        public Builder ipAddress(String ipAddress) {
            return ipAddress(Output.of(ipAddress));
        }

        public SecondaryIPAddressArgs build() {
            $.computeId = Objects.requireNonNull($.computeId, "expected parameter 'computeId' to be non-null");
            $.ipAddress = Objects.requireNonNull($.ipAddress, "expected parameter 'ipAddress' to be non-null");
            return $;
        }
    }

}
