// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SKSNodepoolArgs extends com.pulumi.resources.ResourceArgs {

    public static final SKSNodepoolArgs Empty = new SKSNodepoolArgs();

    /**
     * A list of exoscale.AntiAffinityGroup (IDs) to be attached to the managed instances.
     * 
     */
    @Import(name="antiAffinityGroupIds")
    private @Nullable Output<List<String>> antiAffinityGroupIds;

    /**
     * @return A list of exoscale.AntiAffinityGroup (IDs) to be attached to the managed instances.
     * 
     */
    public Optional<Output<List<String>>> antiAffinityGroupIds() {
        return Optional.ofNullable(this.antiAffinityGroupIds);
    }

    /**
     * The parent exoscale.SKSCluster ID.
     * 
     */
    @Import(name="clusterId", required=true)
    private Output<String> clusterId;

    /**
     * @return The parent exoscale.SKSCluster ID.
     * 
     */
    public Output<String> clusterId() {
        return this.clusterId;
    }

    /**
     * A deploy target ID.
     * 
     */
    @Import(name="deployTargetId")
    private @Nullable Output<String> deployTargetId;

    /**
     * @return A deploy target ID.
     * 
     */
    public Optional<Output<String>> deployTargetId() {
        return Optional.ofNullable(this.deployTargetId);
    }

    /**
     * A free-form text describing the pool.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return A free-form text describing the pool.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The managed instances disk size (GiB; default: `50`).
     * 
     */
    @Import(name="diskSize")
    private @Nullable Output<Integer> diskSize;

    /**
     * @return The managed instances disk size (GiB; default: `50`).
     * 
     */
    public Optional<Output<Integer>> diskSize() {
        return Optional.ofNullable(this.diskSize);
    }

    /**
     * The string used to prefix the managed instances name (default `pool`).
     * 
     */
    @Import(name="instancePrefix")
    private @Nullable Output<String> instancePrefix;

    /**
     * @return The string used to prefix the managed instances name (default `pool`).
     * 
     */
    public Optional<Output<String>> instancePrefix() {
        return Optional.ofNullable(this.instancePrefix);
    }

    /**
     * The managed compute instances type (`&lt;family&gt;.&lt;size&gt;`, e.g. `standard.medium`; use the [Exoscale CLI][cli] - `exo compute instance-type list` - for the list of available types).
     * 
     */
    @Import(name="instanceType", required=true)
    private Output<String> instanceType;

    /**
     * @return The managed compute instances type (`&lt;family&gt;.&lt;size&gt;`, e.g. `standard.medium`; use the [Exoscale CLI][cli] - `exo compute instance-type list` - for the list of available types).
     * 
     */
    public Output<String> instanceType() {
        return this.instanceType;
    }

    /**
     * A map of key/value labels.
     * 
     */
    @Import(name="labels")
    private @Nullable Output<Map<String,String>> labels;

    /**
     * @return A map of key/value labels.
     * 
     */
    public Optional<Output<Map<String,String>>> labels() {
        return Optional.ofNullable(this.labels);
    }

    /**
     * The SKS node pool name.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The SKS node pool name.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * A list of exoscale.PrivateNetwork (IDs) to be attached to the managed instances.
     * 
     */
    @Import(name="privateNetworkIds")
    private @Nullable Output<List<String>> privateNetworkIds;

    /**
     * @return A list of exoscale.PrivateNetwork (IDs) to be attached to the managed instances.
     * 
     */
    public Optional<Output<List<String>>> privateNetworkIds() {
        return Optional.ofNullable(this.privateNetworkIds);
    }

    /**
     * A list of exoscale.SecurityGroup (IDs) to be attached to the managed instances.
     * 
     */
    @Import(name="securityGroupIds")
    private @Nullable Output<List<String>> securityGroupIds;

    /**
     * @return A list of exoscale.SecurityGroup (IDs) to be attached to the managed instances.
     * 
     */
    public Optional<Output<List<String>>> securityGroupIds() {
        return Optional.ofNullable(this.securityGroupIds);
    }

    @Import(name="size", required=true)
    private Output<Integer> size;

    public Output<Integer> size() {
        return this.size;
    }

    /**
     * A map of key/value Kubernetes [taints][taints] (`&lt;value&gt;:&lt;effect&gt;`).
     * 
     */
    @Import(name="taints")
    private @Nullable Output<Map<String,String>> taints;

    /**
     * @return A map of key/value Kubernetes [taints][taints] (`&lt;value&gt;:&lt;effect&gt;`).
     * 
     */
    public Optional<Output<Map<String,String>>> taints() {
        return Optional.ofNullable(this.taints);
    }

    /**
     * The Exoscale [Zone][zone] name.
     * 
     */
    @Import(name="zone", required=true)
    private Output<String> zone;

    /**
     * @return The Exoscale [Zone][zone] name.
     * 
     */
    public Output<String> zone() {
        return this.zone;
    }

    private SKSNodepoolArgs() {}

    private SKSNodepoolArgs(SKSNodepoolArgs $) {
        this.antiAffinityGroupIds = $.antiAffinityGroupIds;
        this.clusterId = $.clusterId;
        this.deployTargetId = $.deployTargetId;
        this.description = $.description;
        this.diskSize = $.diskSize;
        this.instancePrefix = $.instancePrefix;
        this.instanceType = $.instanceType;
        this.labels = $.labels;
        this.name = $.name;
        this.privateNetworkIds = $.privateNetworkIds;
        this.securityGroupIds = $.securityGroupIds;
        this.size = $.size;
        this.taints = $.taints;
        this.zone = $.zone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SKSNodepoolArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SKSNodepoolArgs $;

        public Builder() {
            $ = new SKSNodepoolArgs();
        }

        public Builder(SKSNodepoolArgs defaults) {
            $ = new SKSNodepoolArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param antiAffinityGroupIds A list of exoscale.AntiAffinityGroup (IDs) to be attached to the managed instances.
         * 
         * @return builder
         * 
         */
        public Builder antiAffinityGroupIds(@Nullable Output<List<String>> antiAffinityGroupIds) {
            $.antiAffinityGroupIds = antiAffinityGroupIds;
            return this;
        }

        /**
         * @param antiAffinityGroupIds A list of exoscale.AntiAffinityGroup (IDs) to be attached to the managed instances.
         * 
         * @return builder
         * 
         */
        public Builder antiAffinityGroupIds(List<String> antiAffinityGroupIds) {
            return antiAffinityGroupIds(Output.of(antiAffinityGroupIds));
        }

        /**
         * @param antiAffinityGroupIds A list of exoscale.AntiAffinityGroup (IDs) to be attached to the managed instances.
         * 
         * @return builder
         * 
         */
        public Builder antiAffinityGroupIds(String... antiAffinityGroupIds) {
            return antiAffinityGroupIds(List.of(antiAffinityGroupIds));
        }

        /**
         * @param clusterId The parent exoscale.SKSCluster ID.
         * 
         * @return builder
         * 
         */
        public Builder clusterId(Output<String> clusterId) {
            $.clusterId = clusterId;
            return this;
        }

        /**
         * @param clusterId The parent exoscale.SKSCluster ID.
         * 
         * @return builder
         * 
         */
        public Builder clusterId(String clusterId) {
            return clusterId(Output.of(clusterId));
        }

        /**
         * @param deployTargetId A deploy target ID.
         * 
         * @return builder
         * 
         */
        public Builder deployTargetId(@Nullable Output<String> deployTargetId) {
            $.deployTargetId = deployTargetId;
            return this;
        }

        /**
         * @param deployTargetId A deploy target ID.
         * 
         * @return builder
         * 
         */
        public Builder deployTargetId(String deployTargetId) {
            return deployTargetId(Output.of(deployTargetId));
        }

        /**
         * @param description A free-form text describing the pool.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description A free-form text describing the pool.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param diskSize The managed instances disk size (GiB; default: `50`).
         * 
         * @return builder
         * 
         */
        public Builder diskSize(@Nullable Output<Integer> diskSize) {
            $.diskSize = diskSize;
            return this;
        }

        /**
         * @param diskSize The managed instances disk size (GiB; default: `50`).
         * 
         * @return builder
         * 
         */
        public Builder diskSize(Integer diskSize) {
            return diskSize(Output.of(diskSize));
        }

        /**
         * @param instancePrefix The string used to prefix the managed instances name (default `pool`).
         * 
         * @return builder
         * 
         */
        public Builder instancePrefix(@Nullable Output<String> instancePrefix) {
            $.instancePrefix = instancePrefix;
            return this;
        }

        /**
         * @param instancePrefix The string used to prefix the managed instances name (default `pool`).
         * 
         * @return builder
         * 
         */
        public Builder instancePrefix(String instancePrefix) {
            return instancePrefix(Output.of(instancePrefix));
        }

        /**
         * @param instanceType The managed compute instances type (`&lt;family&gt;.&lt;size&gt;`, e.g. `standard.medium`; use the [Exoscale CLI][cli] - `exo compute instance-type list` - for the list of available types).
         * 
         * @return builder
         * 
         */
        public Builder instanceType(Output<String> instanceType) {
            $.instanceType = instanceType;
            return this;
        }

        /**
         * @param instanceType The managed compute instances type (`&lt;family&gt;.&lt;size&gt;`, e.g. `standard.medium`; use the [Exoscale CLI][cli] - `exo compute instance-type list` - for the list of available types).
         * 
         * @return builder
         * 
         */
        public Builder instanceType(String instanceType) {
            return instanceType(Output.of(instanceType));
        }

        /**
         * @param labels A map of key/value labels.
         * 
         * @return builder
         * 
         */
        public Builder labels(@Nullable Output<Map<String,String>> labels) {
            $.labels = labels;
            return this;
        }

        /**
         * @param labels A map of key/value labels.
         * 
         * @return builder
         * 
         */
        public Builder labels(Map<String,String> labels) {
            return labels(Output.of(labels));
        }

        /**
         * @param name The SKS node pool name.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The SKS node pool name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param privateNetworkIds A list of exoscale.PrivateNetwork (IDs) to be attached to the managed instances.
         * 
         * @return builder
         * 
         */
        public Builder privateNetworkIds(@Nullable Output<List<String>> privateNetworkIds) {
            $.privateNetworkIds = privateNetworkIds;
            return this;
        }

        /**
         * @param privateNetworkIds A list of exoscale.PrivateNetwork (IDs) to be attached to the managed instances.
         * 
         * @return builder
         * 
         */
        public Builder privateNetworkIds(List<String> privateNetworkIds) {
            return privateNetworkIds(Output.of(privateNetworkIds));
        }

        /**
         * @param privateNetworkIds A list of exoscale.PrivateNetwork (IDs) to be attached to the managed instances.
         * 
         * @return builder
         * 
         */
        public Builder privateNetworkIds(String... privateNetworkIds) {
            return privateNetworkIds(List.of(privateNetworkIds));
        }

        /**
         * @param securityGroupIds A list of exoscale.SecurityGroup (IDs) to be attached to the managed instances.
         * 
         * @return builder
         * 
         */
        public Builder securityGroupIds(@Nullable Output<List<String>> securityGroupIds) {
            $.securityGroupIds = securityGroupIds;
            return this;
        }

        /**
         * @param securityGroupIds A list of exoscale.SecurityGroup (IDs) to be attached to the managed instances.
         * 
         * @return builder
         * 
         */
        public Builder securityGroupIds(List<String> securityGroupIds) {
            return securityGroupIds(Output.of(securityGroupIds));
        }

        /**
         * @param securityGroupIds A list of exoscale.SecurityGroup (IDs) to be attached to the managed instances.
         * 
         * @return builder
         * 
         */
        public Builder securityGroupIds(String... securityGroupIds) {
            return securityGroupIds(List.of(securityGroupIds));
        }

        public Builder size(Output<Integer> size) {
            $.size = size;
            return this;
        }

        public Builder size(Integer size) {
            return size(Output.of(size));
        }

        /**
         * @param taints A map of key/value Kubernetes [taints][taints] (`&lt;value&gt;:&lt;effect&gt;`).
         * 
         * @return builder
         * 
         */
        public Builder taints(@Nullable Output<Map<String,String>> taints) {
            $.taints = taints;
            return this;
        }

        /**
         * @param taints A map of key/value Kubernetes [taints][taints] (`&lt;value&gt;:&lt;effect&gt;`).
         * 
         * @return builder
         * 
         */
        public Builder taints(Map<String,String> taints) {
            return taints(Output.of(taints));
        }

        /**
         * @param zone The Exoscale [Zone][zone] name.
         * 
         * @return builder
         * 
         */
        public Builder zone(Output<String> zone) {
            $.zone = zone;
            return this;
        }

        /**
         * @param zone The Exoscale [Zone][zone] name.
         * 
         * @return builder
         * 
         */
        public Builder zone(String zone) {
            return zone(Output.of(zone));
        }

        public SKSNodepoolArgs build() {
            $.clusterId = Objects.requireNonNull($.clusterId, "expected parameter 'clusterId' to be non-null");
            $.instanceType = Objects.requireNonNull($.instanceType, "expected parameter 'instanceType' to be non-null");
            $.size = Objects.requireNonNull($.size, "expected parameter 'size' to be non-null");
            $.zone = Objects.requireNonNull($.zone, "expected parameter 'zone' to be non-null");
            return $;
        }
    }

}
