// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SSHKeyArgs extends com.pulumi.resources.ResourceArgs {

    public static final SSHKeyArgs Empty = new SSHKeyArgs();

    /**
     * The SSH key name.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The SSH key name.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The SSH *public* key that will be authorized in compute instances.
     * 
     */
    @Import(name="publicKey")
    private @Nullable Output<String> publicKey;

    /**
     * @return The SSH *public* key that will be authorized in compute instances.
     * 
     */
    public Optional<Output<String>> publicKey() {
        return Optional.ofNullable(this.publicKey);
    }

    private SSHKeyArgs() {}

    private SSHKeyArgs(SSHKeyArgs $) {
        this.name = $.name;
        this.publicKey = $.publicKey;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SSHKeyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SSHKeyArgs $;

        public Builder() {
            $ = new SSHKeyArgs();
        }

        public Builder(SSHKeyArgs defaults) {
            $ = new SSHKeyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The SSH key name.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The SSH key name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param publicKey The SSH *public* key that will be authorized in compute instances.
         * 
         * @return builder
         * 
         */
        public Builder publicKey(@Nullable Output<String> publicKey) {
            $.publicKey = publicKey;
            return this;
        }

        /**
         * @param publicKey The SSH *public* key that will be authorized in compute instances.
         * 
         * @return builder
         * 
         */
        public Builder publicKey(String publicKey) {
            return publicKey(Output.of(publicKey));
        }

        public SSHKeyArgs build() {
            return $;
        }
    }

}
