// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ComputeInstanceNetworkInterface {
    /**
     * @return The IPv4 address to request as static DHCP lease if the network interface is attached to a *managed* private network.
     * 
     */
    private @Nullable String ipAddress;
    /**
     * @return The exoscale.PrivateNetwork (ID) to attach to the instance.
     * 
     */
    private String networkId;

    private ComputeInstanceNetworkInterface() {}
    /**
     * @return The IPv4 address to request as static DHCP lease if the network interface is attached to a *managed* private network.
     * 
     */
    public Optional<String> ipAddress() {
        return Optional.ofNullable(this.ipAddress);
    }
    /**
     * @return The exoscale.PrivateNetwork (ID) to attach to the instance.
     * 
     */
    public String networkId() {
        return this.networkId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ComputeInstanceNetworkInterface defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String ipAddress;
        private String networkId;
        public Builder() {}
        public Builder(ComputeInstanceNetworkInterface defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ipAddress = defaults.ipAddress;
    	      this.networkId = defaults.networkId;
        }

        @CustomType.Setter
        public Builder ipAddress(@Nullable String ipAddress) {
            this.ipAddress = ipAddress;
            return this;
        }
        @CustomType.Setter
        public Builder networkId(String networkId) {
            this.networkId = Objects.requireNonNull(networkId);
            return this;
        }
        public ComputeInstanceNetworkInterface build() {
            final var o = new ComputeInstanceNetworkInterface();
            o.ipAddress = ipAddress;
            o.networkId = networkId;
            return o;
        }
    }
}
