// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetAntiAffinityGroupResult {
    private @Nullable String id;
    /**
     * @return The list of attached exoscale.ComputeInstance (IDs).
     * 
     */
    private List<String> instances;
    private @Nullable String name;

    private GetAntiAffinityGroupResult() {}
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    /**
     * @return The list of attached exoscale.ComputeInstance (IDs).
     * 
     */
    public List<String> instances() {
        return this.instances;
    }
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAntiAffinityGroupResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String id;
        private List<String> instances;
        private @Nullable String name;
        public Builder() {}
        public Builder(GetAntiAffinityGroupResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.instances = defaults.instances;
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder instances(List<String> instances) {
            this.instances = Objects.requireNonNull(instances);
            return this;
        }
        public Builder instances(String... instances) {
            return instances(List.of(instances));
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }
        public GetAntiAffinityGroupResult build() {
            final var o = new GetAntiAffinityGroupResult();
            o.id = id;
            o.instances = instances;
            o.name = name;
            return o;
        }
    }
}
