// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumiverse.exoscale.outputs.GetComputeInstanceListInstance;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetComputeInstanceListResult {
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private List<GetComputeInstanceListInstance> instances;
    private String zone;

    private GetComputeInstanceListResult() {}
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public List<GetComputeInstanceListInstance> instances() {
        return this.instances;
    }
    public String zone() {
        return this.zone;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetComputeInstanceListResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private List<GetComputeInstanceListInstance> instances;
        private String zone;
        public Builder() {}
        public Builder(GetComputeInstanceListResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.instances = defaults.instances;
    	      this.zone = defaults.zone;
        }

        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder instances(List<GetComputeInstanceListInstance> instances) {
            this.instances = Objects.requireNonNull(instances);
            return this;
        }
        public Builder instances(GetComputeInstanceListInstance... instances) {
            return instances(List.of(instances));
        }
        @CustomType.Setter
        public Builder zone(String zone) {
            this.zone = Objects.requireNonNull(zone);
            return this;
        }
        public GetComputeInstanceListResult build() {
            final var o = new GetComputeInstanceListResult();
            o.id = id;
            o.instances = instances;
            o.zone = zone;
            return o;
        }
    }
}
