// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumiverse.exoscale.outputs.GetDomainRecordFilter;
import com.pulumiverse.exoscale.outputs.GetDomainRecordRecord;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetDomainRecordResult {
    private String domain;
    private GetDomainRecordFilter filter;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return The list of matching records. Structure is documented below.
     * 
     */
    private List<GetDomainRecordRecord> records;

    private GetDomainRecordResult() {}
    public String domain() {
        return this.domain;
    }
    public GetDomainRecordFilter filter() {
        return this.filter;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The list of matching records. Structure is documented below.
     * 
     */
    public List<GetDomainRecordRecord> records() {
        return this.records;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDomainRecordResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String domain;
        private GetDomainRecordFilter filter;
        private String id;
        private List<GetDomainRecordRecord> records;
        public Builder() {}
        public Builder(GetDomainRecordResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.domain = defaults.domain;
    	      this.filter = defaults.filter;
    	      this.id = defaults.id;
    	      this.records = defaults.records;
        }

        @CustomType.Setter
        public Builder domain(String domain) {
            this.domain = Objects.requireNonNull(domain);
            return this;
        }
        @CustomType.Setter
        public Builder filter(GetDomainRecordFilter filter) {
            this.filter = Objects.requireNonNull(filter);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder records(List<GetDomainRecordRecord> records) {
            this.records = Objects.requireNonNull(records);
            return this;
        }
        public Builder records(GetDomainRecordRecord... records) {
            return records(List.of(records));
        }
        public GetDomainRecordResult build() {
            final var o = new GetDomainRecordResult();
            o.domain = domain;
            o.filter = filter;
            o.id = id;
            o.records = records;
            return o;
        }
    }
}
