// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetDomainRecordRecord {
    /**
     * @return The domain record content.
     * 
     */
    private @Nullable String content;
    /**
     * @return The exoscale.Domain name to match.
     * 
     */
    private @Nullable String domain;
    /**
     * @return The record ID to match.
     * 
     */
    private @Nullable String id;
    /**
     * @return The domain record name to match.
     * 
     */
    private @Nullable String name;
    /**
     * @return The record priority.
     * 
     */
    private @Nullable Integer prio;
    /**
     * @return The record type to match.
     * 
     */
    private @Nullable String recordType;
    /**
     * @return The record TTL.
     * 
     */
    private @Nullable Integer ttl;

    private GetDomainRecordRecord() {}
    /**
     * @return The domain record content.
     * 
     */
    public Optional<String> content() {
        return Optional.ofNullable(this.content);
    }
    /**
     * @return The exoscale.Domain name to match.
     * 
     */
    public Optional<String> domain() {
        return Optional.ofNullable(this.domain);
    }
    /**
     * @return The record ID to match.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    /**
     * @return The domain record name to match.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return The record priority.
     * 
     */
    public Optional<Integer> prio() {
        return Optional.ofNullable(this.prio);
    }
    /**
     * @return The record type to match.
     * 
     */
    public Optional<String> recordType() {
        return Optional.ofNullable(this.recordType);
    }
    /**
     * @return The record TTL.
     * 
     */
    public Optional<Integer> ttl() {
        return Optional.ofNullable(this.ttl);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDomainRecordRecord defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String content;
        private @Nullable String domain;
        private @Nullable String id;
        private @Nullable String name;
        private @Nullable Integer prio;
        private @Nullable String recordType;
        private @Nullable Integer ttl;
        public Builder() {}
        public Builder(GetDomainRecordRecord defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.content = defaults.content;
    	      this.domain = defaults.domain;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.prio = defaults.prio;
    	      this.recordType = defaults.recordType;
    	      this.ttl = defaults.ttl;
        }

        @CustomType.Setter
        public Builder content(@Nullable String content) {
            this.content = content;
            return this;
        }
        @CustomType.Setter
        public Builder domain(@Nullable String domain) {
            this.domain = domain;
            return this;
        }
        @CustomType.Setter
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder prio(@Nullable Integer prio) {
            this.prio = prio;
            return this;
        }
        @CustomType.Setter
        public Builder recordType(@Nullable String recordType) {
            this.recordType = recordType;
            return this;
        }
        @CustomType.Setter
        public Builder ttl(@Nullable Integer ttl) {
            this.ttl = ttl;
            return this;
        }
        public GetDomainRecordRecord build() {
            final var o = new GetDomainRecordRecord();
            o.content = content;
            o.domain = domain;
            o.id = id;
            o.name = name;
            o.prio = prio;
            o.recordType = recordType;
            o.ttl = ttl;
            return o;
        }
    }
}
