// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumiverse.exoscale.outputs.GetElasticIPHealthcheck;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetElasticIPResult {
    /**
     * @return The Elastic IP (EIP) address family (`inet4` or `inet6`).
     * 
     */
    private String addressFamily;
    /**
     * @return The Elastic IP (EIP) CIDR.
     * 
     */
    private String cidr;
    /**
     * @return The Elastic IP (EIP) description.
     * 
     */
    private String description;
    /**
     * @return (Block) The *managed* EIP healthcheck configuration. Structure is documented below.
     * 
     */
    private List<GetElasticIPHealthcheck> healthchecks;
    private @Nullable String id;
    private @Nullable String ipAddress;
    private String zone;

    private GetElasticIPResult() {}
    /**
     * @return The Elastic IP (EIP) address family (`inet4` or `inet6`).
     * 
     */
    public String addressFamily() {
        return this.addressFamily;
    }
    /**
     * @return The Elastic IP (EIP) CIDR.
     * 
     */
    public String cidr() {
        return this.cidr;
    }
    /**
     * @return The Elastic IP (EIP) description.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return (Block) The *managed* EIP healthcheck configuration. Structure is documented below.
     * 
     */
    public List<GetElasticIPHealthcheck> healthchecks() {
        return this.healthchecks;
    }
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    public Optional<String> ipAddress() {
        return Optional.ofNullable(this.ipAddress);
    }
    public String zone() {
        return this.zone;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetElasticIPResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String addressFamily;
        private String cidr;
        private String description;
        private List<GetElasticIPHealthcheck> healthchecks;
        private @Nullable String id;
        private @Nullable String ipAddress;
        private String zone;
        public Builder() {}
        public Builder(GetElasticIPResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.addressFamily = defaults.addressFamily;
    	      this.cidr = defaults.cidr;
    	      this.description = defaults.description;
    	      this.healthchecks = defaults.healthchecks;
    	      this.id = defaults.id;
    	      this.ipAddress = defaults.ipAddress;
    	      this.zone = defaults.zone;
        }

        @CustomType.Setter
        public Builder addressFamily(String addressFamily) {
            this.addressFamily = Objects.requireNonNull(addressFamily);
            return this;
        }
        @CustomType.Setter
        public Builder cidr(String cidr) {
            this.cidr = Objects.requireNonNull(cidr);
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            this.description = Objects.requireNonNull(description);
            return this;
        }
        @CustomType.Setter
        public Builder healthchecks(List<GetElasticIPHealthcheck> healthchecks) {
            this.healthchecks = Objects.requireNonNull(healthchecks);
            return this;
        }
        public Builder healthchecks(GetElasticIPHealthcheck... healthchecks) {
            return healthchecks(List.of(healthchecks));
        }
        @CustomType.Setter
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder ipAddress(@Nullable String ipAddress) {
            this.ipAddress = ipAddress;
            return this;
        }
        @CustomType.Setter
        public Builder zone(String zone) {
            this.zone = Objects.requireNonNull(zone);
            return this;
        }
        public GetElasticIPResult build() {
            final var o = new GetElasticIPResult();
            o.addressFamily = addressFamily;
            o.cidr = cidr;
            o.description = description;
            o.healthchecks = healthchecks;
            o.id = id;
            o.ipAddress = ipAddress;
            o.zone = zone;
            return o;
        }
    }
}
