// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class InstancePoolInstance {
    /**
     * @return The compute instance ID.
     * 
     */
    private @Nullable String id;
    /**
     * @return The instance (main network interface) IPv6 address.
     * 
     */
    private @Nullable String ipv6Address;
    /**
     * @return The instance pool name.
     * 
     */
    private @Nullable String name;
    /**
     * @return The instance (main network interface) IPv4 address.
     * 
     */
    private @Nullable String publicIpAddress;

    private InstancePoolInstance() {}
    /**
     * @return The compute instance ID.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    /**
     * @return The instance (main network interface) IPv6 address.
     * 
     */
    public Optional<String> ipv6Address() {
        return Optional.ofNullable(this.ipv6Address);
    }
    /**
     * @return The instance pool name.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return The instance (main network interface) IPv4 address.
     * 
     */
    public Optional<String> publicIpAddress() {
        return Optional.ofNullable(this.publicIpAddress);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(InstancePoolInstance defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String id;
        private @Nullable String ipv6Address;
        private @Nullable String name;
        private @Nullable String publicIpAddress;
        public Builder() {}
        public Builder(InstancePoolInstance defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.ipv6Address = defaults.ipv6Address;
    	      this.name = defaults.name;
    	      this.publicIpAddress = defaults.publicIpAddress;
        }

        @CustomType.Setter
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder ipv6Address(@Nullable String ipv6Address) {
            this.ipv6Address = ipv6Address;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder publicIpAddress(@Nullable String publicIpAddress) {
            this.publicIpAddress = publicIpAddress;
            return this;
        }
        public InstancePoolInstance build() {
            final var o = new InstancePoolInstance();
            o.id = id;
            o.ipv6Address = ipv6Address;
            o.name = name;
            o.publicIpAddress = publicIpAddress;
            return o;
        }
    }
}
