// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class SKSClusterOidc {
    /**
     * @return The OpenID client ID.
     * 
     */
    private String clientId;
    /**
     * @return An OpenID JWT claim to use as the user&#39;s group.
     * 
     */
    private @Nullable String groupsClaim;
    /**
     * @return An OpenID prefix prepended to group claims.
     * 
     */
    private @Nullable String groupsPrefix;
    /**
     * @return The OpenID provider URL.
     * 
     */
    private String issuerUrl;
    /**
     * @return A map of key/value pairs that describes a required claim in the OpenID Token.
     * 
     */
    private @Nullable Map<String,String> requiredClaim;
    /**
     * @return An OpenID JWT claim to use as the user name.
     * 
     */
    private @Nullable String usernameClaim;
    /**
     * @return An OpenID prefix prepended to username claims.
     * 
     */
    private @Nullable String usernamePrefix;

    private SKSClusterOidc() {}
    /**
     * @return The OpenID client ID.
     * 
     */
    public String clientId() {
        return this.clientId;
    }
    /**
     * @return An OpenID JWT claim to use as the user&#39;s group.
     * 
     */
    public Optional<String> groupsClaim() {
        return Optional.ofNullable(this.groupsClaim);
    }
    /**
     * @return An OpenID prefix prepended to group claims.
     * 
     */
    public Optional<String> groupsPrefix() {
        return Optional.ofNullable(this.groupsPrefix);
    }
    /**
     * @return The OpenID provider URL.
     * 
     */
    public String issuerUrl() {
        return this.issuerUrl;
    }
    /**
     * @return A map of key/value pairs that describes a required claim in the OpenID Token.
     * 
     */
    public Map<String,String> requiredClaim() {
        return this.requiredClaim == null ? Map.of() : this.requiredClaim;
    }
    /**
     * @return An OpenID JWT claim to use as the user name.
     * 
     */
    public Optional<String> usernameClaim() {
        return Optional.ofNullable(this.usernameClaim);
    }
    /**
     * @return An OpenID prefix prepended to username claims.
     * 
     */
    public Optional<String> usernamePrefix() {
        return Optional.ofNullable(this.usernamePrefix);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SKSClusterOidc defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String clientId;
        private @Nullable String groupsClaim;
        private @Nullable String groupsPrefix;
        private String issuerUrl;
        private @Nullable Map<String,String> requiredClaim;
        private @Nullable String usernameClaim;
        private @Nullable String usernamePrefix;
        public Builder() {}
        public Builder(SKSClusterOidc defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.clientId = defaults.clientId;
    	      this.groupsClaim = defaults.groupsClaim;
    	      this.groupsPrefix = defaults.groupsPrefix;
    	      this.issuerUrl = defaults.issuerUrl;
    	      this.requiredClaim = defaults.requiredClaim;
    	      this.usernameClaim = defaults.usernameClaim;
    	      this.usernamePrefix = defaults.usernamePrefix;
        }

        @CustomType.Setter
        public Builder clientId(String clientId) {
            this.clientId = Objects.requireNonNull(clientId);
            return this;
        }
        @CustomType.Setter
        public Builder groupsClaim(@Nullable String groupsClaim) {
            this.groupsClaim = groupsClaim;
            return this;
        }
        @CustomType.Setter
        public Builder groupsPrefix(@Nullable String groupsPrefix) {
            this.groupsPrefix = groupsPrefix;
            return this;
        }
        @CustomType.Setter
        public Builder issuerUrl(String issuerUrl) {
            this.issuerUrl = Objects.requireNonNull(issuerUrl);
            return this;
        }
        @CustomType.Setter
        public Builder requiredClaim(@Nullable Map<String,String> requiredClaim) {
            this.requiredClaim = requiredClaim;
            return this;
        }
        @CustomType.Setter
        public Builder usernameClaim(@Nullable String usernameClaim) {
            this.usernameClaim = usernameClaim;
            return this;
        }
        @CustomType.Setter
        public Builder usernamePrefix(@Nullable String usernamePrefix) {
            this.usernamePrefix = usernamePrefix;
            return this;
        }
        public SKSClusterOidc build() {
            final var o = new SKSClusterOidc();
            o.clientId = clientId;
            o.groupsClaim = groupsClaim;
            o.groupsPrefix = groupsPrefix;
            o.issuerUrl = issuerUrl;
            o.requiredClaim = requiredClaim;
            o.usernameClaim = usernameClaim;
            o.usernamePrefix = usernamePrefix;
            return o;
        }
    }
}
