// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumiverse.exoscale.inputs.DatabaseKafkaArgs;
import com.pulumiverse.exoscale.inputs.DatabaseMysqlArgs;
import com.pulumiverse.exoscale.inputs.DatabaseOpensearchArgs;
import com.pulumiverse.exoscale.inputs.DatabasePgArgs;
import com.pulumiverse.exoscale.inputs.DatabaseRedisArgs;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DatabaseState extends com.pulumi.resources.ResourceArgs {

    public static final DatabaseState Empty = new DatabaseState();

    /**
     * CA Certificate required to reach a DBaaS service through a TLS-protected connection.
     * 
     */
    @Import(name="caCertificate")
    private @Nullable Output<String> caCertificate;

    /**
     * @return CA Certificate required to reach a DBaaS service through a TLS-protected connection.
     * 
     */
    public Optional<Output<String>> caCertificate() {
        return Optional.ofNullable(this.caCertificate);
    }

    /**
     * The creation date of the database service.
     * 
     */
    @Import(name="createdAt")
    private @Nullable Output<String> createdAt;

    /**
     * @return The creation date of the database service.
     * 
     */
    public Optional<Output<String>> createdAt() {
        return Optional.ofNullable(this.createdAt);
    }

    /**
     * The disk size of the database service.
     * 
     */
    @Import(name="diskSize")
    private @Nullable Output<Integer> diskSize;

    /**
     * @return The disk size of the database service.
     * 
     */
    public Optional<Output<Integer>> diskSize() {
        return Optional.ofNullable(this.diskSize);
    }

    /**
     * *kafka* database service type specific arguments. Structure is documented below.
     * 
     */
    @Import(name="kafka")
    private @Nullable Output<DatabaseKafkaArgs> kafka;

    /**
     * @return *kafka* database service type specific arguments. Structure is documented below.
     * 
     */
    public Optional<Output<DatabaseKafkaArgs>> kafka() {
        return Optional.ofNullable(this.kafka);
    }

    /**
     * The day of week to perform the automated database service maintenance (`never`, `monday`, `tuesday`, `wednesday`, `thursday`, `friday`, `saturday`, `sunday`).
     * 
     */
    @Import(name="maintenanceDow")
    private @Nullable Output<String> maintenanceDow;

    /**
     * @return The day of week to perform the automated database service maintenance (`never`, `monday`, `tuesday`, `wednesday`, `thursday`, `friday`, `saturday`, `sunday`).
     * 
     */
    public Optional<Output<String>> maintenanceDow() {
        return Optional.ofNullable(this.maintenanceDow);
    }

    /**
     * The time of day to perform the automated database service maintenance (`HH:MM:SS`)
     * 
     */
    @Import(name="maintenanceTime")
    private @Nullable Output<String> maintenanceTime;

    /**
     * @return The time of day to perform the automated database service maintenance (`HH:MM:SS`)
     * 
     */
    public Optional<Output<String>> maintenanceTime() {
        return Optional.ofNullable(this.maintenanceTime);
    }

    /**
     * *mysql* database service type specific arguments. Structure is documented below.
     * 
     */
    @Import(name="mysql")
    private @Nullable Output<DatabaseMysqlArgs> mysql;

    /**
     * @return *mysql* database service type specific arguments. Structure is documented below.
     * 
     */
    public Optional<Output<DatabaseMysqlArgs>> mysql() {
        return Optional.ofNullable(this.mysql);
    }

    /**
     * The name of the database service.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the database service.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The number of CPUs of the database service.
     * 
     */
    @Import(name="nodeCpus")
    private @Nullable Output<Integer> nodeCpus;

    /**
     * @return The number of CPUs of the database service.
     * 
     */
    public Optional<Output<Integer>> nodeCpus() {
        return Optional.ofNullable(this.nodeCpus);
    }

    /**
     * The amount of memory of the database service.
     * 
     */
    @Import(name="nodeMemory")
    private @Nullable Output<Integer> nodeMemory;

    /**
     * @return The amount of memory of the database service.
     * 
     */
    public Optional<Output<Integer>> nodeMemory() {
        return Optional.ofNullable(this.nodeMemory);
    }

    /**
     * The number of nodes of the database service.
     * 
     */
    @Import(name="nodes")
    private @Nullable Output<Integer> nodes;

    /**
     * @return The number of nodes of the database service.
     * 
     */
    public Optional<Output<Integer>> nodes() {
        return Optional.ofNullable(this.nodes);
    }

    /**
     * *opensearch* database service type specific arguments. Structure is documented below.
     * 
     */
    @Import(name="opensearch")
    private @Nullable Output<DatabaseOpensearchArgs> opensearch;

    /**
     * @return *opensearch* database service type specific arguments. Structure is documented below.
     * 
     */
    public Optional<Output<DatabaseOpensearchArgs>> opensearch() {
        return Optional.ofNullable(this.opensearch);
    }

    /**
     * *pg* database service type specific arguments. Structure is documented below.
     * 
     */
    @Import(name="pg")
    private @Nullable Output<DatabasePgArgs> pg;

    /**
     * @return *pg* database service type specific arguments. Structure is documented below.
     * 
     */
    public Optional<Output<DatabasePgArgs>> pg() {
        return Optional.ofNullable(this.pg);
    }

    /**
     * The plan of the database service (use the [Exoscale CLI][cli] - `exo dbaas type show &lt;TYPE&gt;` - for reference).
     * 
     */
    @Import(name="plan")
    private @Nullable Output<String> plan;

    /**
     * @return The plan of the database service (use the [Exoscale CLI][cli] - `exo dbaas type show &lt;TYPE&gt;` - for reference).
     * 
     */
    public Optional<Output<String>> plan() {
        return Optional.ofNullable(this.plan);
    }

    /**
     * *redis* database service type specific arguments. Structure is documented below.
     * 
     */
    @Import(name="redis")
    private @Nullable Output<DatabaseRedisArgs> redis;

    /**
     * @return *redis* database service type specific arguments. Structure is documented below.
     * 
     */
    public Optional<Output<DatabaseRedisArgs>> redis() {
        return Optional.ofNullable(this.redis);
    }

    /**
     * The current state of the database service.
     * 
     */
    @Import(name="state")
    private @Nullable Output<String> state;

    /**
     * @return The current state of the database service.
     * 
     */
    public Optional<Output<String>> state() {
        return Optional.ofNullable(this.state);
    }

    /**
     * The database service protection boolean flag against termination/power-off.
     * 
     */
    @Import(name="terminationProtection")
    private @Nullable Output<Boolean> terminationProtection;

    /**
     * @return The database service protection boolean flag against termination/power-off.
     * 
     */
    public Optional<Output<Boolean>> terminationProtection() {
        return Optional.ofNullable(this.terminationProtection);
    }

    /**
     * The type of the database service (`kafka`, `mysql`, `opensearch`, `pg`, `redis`).
     * 
     */
    @Import(name="type")
    private @Nullable Output<String> type;

    /**
     * @return The type of the database service (`kafka`, `mysql`, `opensearch`, `pg`, `redis`).
     * 
     */
    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    /**
     * The date of the latest database service update.
     * 
     */
    @Import(name="updatedAt")
    private @Nullable Output<String> updatedAt;

    /**
     * @return The date of the latest database service update.
     * 
     */
    public Optional<Output<String>> updatedAt() {
        return Optional.ofNullable(this.updatedAt);
    }

    /**
     * The database service connection URI.
     * 
     */
    @Import(name="uri")
    private @Nullable Output<String> uri;

    /**
     * @return The database service connection URI.
     * 
     */
    public Optional<Output<String>> uri() {
        return Optional.ofNullable(this.uri);
    }

    /**
     * The Exoscale [Zone][zone] name.
     * 
     */
    @Import(name="zone")
    private @Nullable Output<String> zone;

    /**
     * @return The Exoscale [Zone][zone] name.
     * 
     */
    public Optional<Output<String>> zone() {
        return Optional.ofNullable(this.zone);
    }

    private DatabaseState() {}

    private DatabaseState(DatabaseState $) {
        this.caCertificate = $.caCertificate;
        this.createdAt = $.createdAt;
        this.diskSize = $.diskSize;
        this.kafka = $.kafka;
        this.maintenanceDow = $.maintenanceDow;
        this.maintenanceTime = $.maintenanceTime;
        this.mysql = $.mysql;
        this.name = $.name;
        this.nodeCpus = $.nodeCpus;
        this.nodeMemory = $.nodeMemory;
        this.nodes = $.nodes;
        this.opensearch = $.opensearch;
        this.pg = $.pg;
        this.plan = $.plan;
        this.redis = $.redis;
        this.state = $.state;
        this.terminationProtection = $.terminationProtection;
        this.type = $.type;
        this.updatedAt = $.updatedAt;
        this.uri = $.uri;
        this.zone = $.zone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DatabaseState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DatabaseState $;

        public Builder() {
            $ = new DatabaseState();
        }

        public Builder(DatabaseState defaults) {
            $ = new DatabaseState(Objects.requireNonNull(defaults));
        }

        /**
         * @param caCertificate CA Certificate required to reach a DBaaS service through a TLS-protected connection.
         * 
         * @return builder
         * 
         */
        public Builder caCertificate(@Nullable Output<String> caCertificate) {
            $.caCertificate = caCertificate;
            return this;
        }

        /**
         * @param caCertificate CA Certificate required to reach a DBaaS service through a TLS-protected connection.
         * 
         * @return builder
         * 
         */
        public Builder caCertificate(String caCertificate) {
            return caCertificate(Output.of(caCertificate));
        }

        /**
         * @param createdAt The creation date of the database service.
         * 
         * @return builder
         * 
         */
        public Builder createdAt(@Nullable Output<String> createdAt) {
            $.createdAt = createdAt;
            return this;
        }

        /**
         * @param createdAt The creation date of the database service.
         * 
         * @return builder
         * 
         */
        public Builder createdAt(String createdAt) {
            return createdAt(Output.of(createdAt));
        }

        /**
         * @param diskSize The disk size of the database service.
         * 
         * @return builder
         * 
         */
        public Builder diskSize(@Nullable Output<Integer> diskSize) {
            $.diskSize = diskSize;
            return this;
        }

        /**
         * @param diskSize The disk size of the database service.
         * 
         * @return builder
         * 
         */
        public Builder diskSize(Integer diskSize) {
            return diskSize(Output.of(diskSize));
        }

        /**
         * @param kafka *kafka* database service type specific arguments. Structure is documented below.
         * 
         * @return builder
         * 
         */
        public Builder kafka(@Nullable Output<DatabaseKafkaArgs> kafka) {
            $.kafka = kafka;
            return this;
        }

        /**
         * @param kafka *kafka* database service type specific arguments. Structure is documented below.
         * 
         * @return builder
         * 
         */
        public Builder kafka(DatabaseKafkaArgs kafka) {
            return kafka(Output.of(kafka));
        }

        /**
         * @param maintenanceDow The day of week to perform the automated database service maintenance (`never`, `monday`, `tuesday`, `wednesday`, `thursday`, `friday`, `saturday`, `sunday`).
         * 
         * @return builder
         * 
         */
        public Builder maintenanceDow(@Nullable Output<String> maintenanceDow) {
            $.maintenanceDow = maintenanceDow;
            return this;
        }

        /**
         * @param maintenanceDow The day of week to perform the automated database service maintenance (`never`, `monday`, `tuesday`, `wednesday`, `thursday`, `friday`, `saturday`, `sunday`).
         * 
         * @return builder
         * 
         */
        public Builder maintenanceDow(String maintenanceDow) {
            return maintenanceDow(Output.of(maintenanceDow));
        }

        /**
         * @param maintenanceTime The time of day to perform the automated database service maintenance (`HH:MM:SS`)
         * 
         * @return builder
         * 
         */
        public Builder maintenanceTime(@Nullable Output<String> maintenanceTime) {
            $.maintenanceTime = maintenanceTime;
            return this;
        }

        /**
         * @param maintenanceTime The time of day to perform the automated database service maintenance (`HH:MM:SS`)
         * 
         * @return builder
         * 
         */
        public Builder maintenanceTime(String maintenanceTime) {
            return maintenanceTime(Output.of(maintenanceTime));
        }

        /**
         * @param mysql *mysql* database service type specific arguments. Structure is documented below.
         * 
         * @return builder
         * 
         */
        public Builder mysql(@Nullable Output<DatabaseMysqlArgs> mysql) {
            $.mysql = mysql;
            return this;
        }

        /**
         * @param mysql *mysql* database service type specific arguments. Structure is documented below.
         * 
         * @return builder
         * 
         */
        public Builder mysql(DatabaseMysqlArgs mysql) {
            return mysql(Output.of(mysql));
        }

        /**
         * @param name The name of the database service.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the database service.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param nodeCpus The number of CPUs of the database service.
         * 
         * @return builder
         * 
         */
        public Builder nodeCpus(@Nullable Output<Integer> nodeCpus) {
            $.nodeCpus = nodeCpus;
            return this;
        }

        /**
         * @param nodeCpus The number of CPUs of the database service.
         * 
         * @return builder
         * 
         */
        public Builder nodeCpus(Integer nodeCpus) {
            return nodeCpus(Output.of(nodeCpus));
        }

        /**
         * @param nodeMemory The amount of memory of the database service.
         * 
         * @return builder
         * 
         */
        public Builder nodeMemory(@Nullable Output<Integer> nodeMemory) {
            $.nodeMemory = nodeMemory;
            return this;
        }

        /**
         * @param nodeMemory The amount of memory of the database service.
         * 
         * @return builder
         * 
         */
        public Builder nodeMemory(Integer nodeMemory) {
            return nodeMemory(Output.of(nodeMemory));
        }

        /**
         * @param nodes The number of nodes of the database service.
         * 
         * @return builder
         * 
         */
        public Builder nodes(@Nullable Output<Integer> nodes) {
            $.nodes = nodes;
            return this;
        }

        /**
         * @param nodes The number of nodes of the database service.
         * 
         * @return builder
         * 
         */
        public Builder nodes(Integer nodes) {
            return nodes(Output.of(nodes));
        }

        /**
         * @param opensearch *opensearch* database service type specific arguments. Structure is documented below.
         * 
         * @return builder
         * 
         */
        public Builder opensearch(@Nullable Output<DatabaseOpensearchArgs> opensearch) {
            $.opensearch = opensearch;
            return this;
        }

        /**
         * @param opensearch *opensearch* database service type specific arguments. Structure is documented below.
         * 
         * @return builder
         * 
         */
        public Builder opensearch(DatabaseOpensearchArgs opensearch) {
            return opensearch(Output.of(opensearch));
        }

        /**
         * @param pg *pg* database service type specific arguments. Structure is documented below.
         * 
         * @return builder
         * 
         */
        public Builder pg(@Nullable Output<DatabasePgArgs> pg) {
            $.pg = pg;
            return this;
        }

        /**
         * @param pg *pg* database service type specific arguments. Structure is documented below.
         * 
         * @return builder
         * 
         */
        public Builder pg(DatabasePgArgs pg) {
            return pg(Output.of(pg));
        }

        /**
         * @param plan The plan of the database service (use the [Exoscale CLI][cli] - `exo dbaas type show &lt;TYPE&gt;` - for reference).
         * 
         * @return builder
         * 
         */
        public Builder plan(@Nullable Output<String> plan) {
            $.plan = plan;
            return this;
        }

        /**
         * @param plan The plan of the database service (use the [Exoscale CLI][cli] - `exo dbaas type show &lt;TYPE&gt;` - for reference).
         * 
         * @return builder
         * 
         */
        public Builder plan(String plan) {
            return plan(Output.of(plan));
        }

        /**
         * @param redis *redis* database service type specific arguments. Structure is documented below.
         * 
         * @return builder
         * 
         */
        public Builder redis(@Nullable Output<DatabaseRedisArgs> redis) {
            $.redis = redis;
            return this;
        }

        /**
         * @param redis *redis* database service type specific arguments. Structure is documented below.
         * 
         * @return builder
         * 
         */
        public Builder redis(DatabaseRedisArgs redis) {
            return redis(Output.of(redis));
        }

        /**
         * @param state The current state of the database service.
         * 
         * @return builder
         * 
         */
        public Builder state(@Nullable Output<String> state) {
            $.state = state;
            return this;
        }

        /**
         * @param state The current state of the database service.
         * 
         * @return builder
         * 
         */
        public Builder state(String state) {
            return state(Output.of(state));
        }

        /**
         * @param terminationProtection The database service protection boolean flag against termination/power-off.
         * 
         * @return builder
         * 
         */
        public Builder terminationProtection(@Nullable Output<Boolean> terminationProtection) {
            $.terminationProtection = terminationProtection;
            return this;
        }

        /**
         * @param terminationProtection The database service protection boolean flag against termination/power-off.
         * 
         * @return builder
         * 
         */
        public Builder terminationProtection(Boolean terminationProtection) {
            return terminationProtection(Output.of(terminationProtection));
        }

        /**
         * @param type The type of the database service (`kafka`, `mysql`, `opensearch`, `pg`, `redis`).
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type The type of the database service (`kafka`, `mysql`, `opensearch`, `pg`, `redis`).
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        /**
         * @param updatedAt The date of the latest database service update.
         * 
         * @return builder
         * 
         */
        public Builder updatedAt(@Nullable Output<String> updatedAt) {
            $.updatedAt = updatedAt;
            return this;
        }

        /**
         * @param updatedAt The date of the latest database service update.
         * 
         * @return builder
         * 
         */
        public Builder updatedAt(String updatedAt) {
            return updatedAt(Output.of(updatedAt));
        }

        /**
         * @param uri The database service connection URI.
         * 
         * @return builder
         * 
         */
        public Builder uri(@Nullable Output<String> uri) {
            $.uri = uri;
            return this;
        }

        /**
         * @param uri The database service connection URI.
         * 
         * @return builder
         * 
         */
        public Builder uri(String uri) {
            return uri(Output.of(uri));
        }

        /**
         * @param zone The Exoscale [Zone][zone] name.
         * 
         * @return builder
         * 
         */
        public Builder zone(@Nullable Output<String> zone) {
            $.zone = zone;
            return this;
        }

        /**
         * @param zone The Exoscale [Zone][zone] name.
         * 
         * @return builder
         * 
         */
        public Builder zone(String zone) {
            return zone(Output.of(zone));
        }

        public DatabaseState build() {
            return $;
        }
    }

}
