// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DomainRecordState extends com.pulumi.resources.ResourceArgs {

    public static final DomainRecordState Empty = new DomainRecordState();

    /**
     * The record value.
     * 
     */
    @Import(name="content")
    private @Nullable Output<String> content;

    /**
     * @return The record value.
     * 
     */
    public Optional<Output<String>> content() {
        return Optional.ofNullable(this.content);
    }

    /**
     * The parent exoscale.Domain to attach the record to.
     * 
     */
    @Import(name="domain")
    private @Nullable Output<String> domain;

    /**
     * @return The parent exoscale.Domain to attach the record to.
     * 
     */
    public Optional<Output<String>> domain() {
        return Optional.ofNullable(this.domain);
    }

    /**
     * The record *Fully Qualified Domain Name* (FQDN). Useful for aliasing `A`/`AAAA` records with `CNAME`.
     * 
     */
    @Import(name="hostname")
    private @Nullable Output<String> hostname;

    /**
     * @return The record *Fully Qualified Domain Name* (FQDN). Useful for aliasing `A`/`AAAA` records with `CNAME`.
     * 
     */
    public Optional<Output<String>> hostname() {
        return Optional.ofNullable(this.hostname);
    }

    /**
     * The record name, Leave blank (`&#34;&#34;`) to create a root record (similar to using `@` in a DNS zone file).
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The record name, Leave blank (`&#34;&#34;`) to create a root record (similar to using `@` in a DNS zone file).
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The record priority (for types that support it; minimum `0`).
     * 
     */
    @Import(name="prio")
    private @Nullable Output<Integer> prio;

    /**
     * @return The record priority (for types that support it; minimum `0`).
     * 
     */
    public Optional<Output<Integer>> prio() {
        return Optional.ofNullable(this.prio);
    }

    /**
     * The record type (`A`, `AAAA`, `ALIAS`, `CAA`, `CNAME`, `HINFO`, `MX`, `NAPTR`, `NS`, `POOL`, `SPF`, `SRV`, `SSHFP`, `TXT`, `URL`).
     * 
     */
    @Import(name="recordType")
    private @Nullable Output<String> recordType;

    /**
     * @return The record type (`A`, `AAAA`, `ALIAS`, `CAA`, `CNAME`, `HINFO`, `MX`, `NAPTR`, `NS`, `POOL`, `SPF`, `SRV`, `SSHFP`, `TXT`, `URL`).
     * 
     */
    public Optional<Output<String>> recordType() {
        return Optional.ofNullable(this.recordType);
    }

    /**
     * The record TTL (seconds; minimum `0`; default: `3600`).
     * 
     */
    @Import(name="ttl")
    private @Nullable Output<Integer> ttl;

    /**
     * @return The record TTL (seconds; minimum `0`; default: `3600`).
     * 
     */
    public Optional<Output<Integer>> ttl() {
        return Optional.ofNullable(this.ttl);
    }

    private DomainRecordState() {}

    private DomainRecordState(DomainRecordState $) {
        this.content = $.content;
        this.domain = $.domain;
        this.hostname = $.hostname;
        this.name = $.name;
        this.prio = $.prio;
        this.recordType = $.recordType;
        this.ttl = $.ttl;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DomainRecordState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DomainRecordState $;

        public Builder() {
            $ = new DomainRecordState();
        }

        public Builder(DomainRecordState defaults) {
            $ = new DomainRecordState(Objects.requireNonNull(defaults));
        }

        /**
         * @param content The record value.
         * 
         * @return builder
         * 
         */
        public Builder content(@Nullable Output<String> content) {
            $.content = content;
            return this;
        }

        /**
         * @param content The record value.
         * 
         * @return builder
         * 
         */
        public Builder content(String content) {
            return content(Output.of(content));
        }

        /**
         * @param domain The parent exoscale.Domain to attach the record to.
         * 
         * @return builder
         * 
         */
        public Builder domain(@Nullable Output<String> domain) {
            $.domain = domain;
            return this;
        }

        /**
         * @param domain The parent exoscale.Domain to attach the record to.
         * 
         * @return builder
         * 
         */
        public Builder domain(String domain) {
            return domain(Output.of(domain));
        }

        /**
         * @param hostname The record *Fully Qualified Domain Name* (FQDN). Useful for aliasing `A`/`AAAA` records with `CNAME`.
         * 
         * @return builder
         * 
         */
        public Builder hostname(@Nullable Output<String> hostname) {
            $.hostname = hostname;
            return this;
        }

        /**
         * @param hostname The record *Fully Qualified Domain Name* (FQDN). Useful for aliasing `A`/`AAAA` records with `CNAME`.
         * 
         * @return builder
         * 
         */
        public Builder hostname(String hostname) {
            return hostname(Output.of(hostname));
        }

        /**
         * @param name The record name, Leave blank (`&#34;&#34;`) to create a root record (similar to using `@` in a DNS zone file).
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The record name, Leave blank (`&#34;&#34;`) to create a root record (similar to using `@` in a DNS zone file).
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param prio The record priority (for types that support it; minimum `0`).
         * 
         * @return builder
         * 
         */
        public Builder prio(@Nullable Output<Integer> prio) {
            $.prio = prio;
            return this;
        }

        /**
         * @param prio The record priority (for types that support it; minimum `0`).
         * 
         * @return builder
         * 
         */
        public Builder prio(Integer prio) {
            return prio(Output.of(prio));
        }

        /**
         * @param recordType The record type (`A`, `AAAA`, `ALIAS`, `CAA`, `CNAME`, `HINFO`, `MX`, `NAPTR`, `NS`, `POOL`, `SPF`, `SRV`, `SSHFP`, `TXT`, `URL`).
         * 
         * @return builder
         * 
         */
        public Builder recordType(@Nullable Output<String> recordType) {
            $.recordType = recordType;
            return this;
        }

        /**
         * @param recordType The record type (`A`, `AAAA`, `ALIAS`, `CAA`, `CNAME`, `HINFO`, `MX`, `NAPTR`, `NS`, `POOL`, `SPF`, `SRV`, `SSHFP`, `TXT`, `URL`).
         * 
         * @return builder
         * 
         */
        public Builder recordType(String recordType) {
            return recordType(Output.of(recordType));
        }

        /**
         * @param ttl The record TTL (seconds; minimum `0`; default: `3600`).
         * 
         * @return builder
         * 
         */
        public Builder ttl(@Nullable Output<Integer> ttl) {
            $.ttl = ttl;
            return this;
        }

        /**
         * @param ttl The record TTL (seconds; minimum `0`; default: `3600`).
         * 
         * @return builder
         * 
         */
        public Builder ttl(Integer ttl) {
            return ttl(Output.of(ttl));
        }

        public DomainRecordState build() {
            return $;
        }
    }

}
