// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetComputePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetComputePlainArgs Empty = new GetComputePlainArgs();

    /**
     * The instance hostname to match.
     * 
     */
    @Import(name="hostname")
    private @Nullable String hostname;

    /**
     * @return The instance hostname to match.
     * 
     */
    public Optional<String> hostname() {
        return Optional.ofNullable(this.hostname);
    }

    /**
     * The compute instance ID to match.
     * 
     */
    @Import(name="id")
    private @Nullable String id;

    /**
     * @return The compute instance ID to match.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * The instance tags to match (map of key/value).
     * 
     */
    @Import(name="tags")
    private @Nullable Map<String,String> tags;

    /**
     * @return The instance tags to match (map of key/value).
     * 
     */
    public Optional<Map<String,String>> tags() {
        return Optional.ofNullable(this.tags);
    }

    private GetComputePlainArgs() {}

    private GetComputePlainArgs(GetComputePlainArgs $) {
        this.hostname = $.hostname;
        this.id = $.id;
        this.tags = $.tags;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetComputePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetComputePlainArgs $;

        public Builder() {
            $ = new GetComputePlainArgs();
        }

        public Builder(GetComputePlainArgs defaults) {
            $ = new GetComputePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param hostname The instance hostname to match.
         * 
         * @return builder
         * 
         */
        public Builder hostname(@Nullable String hostname) {
            $.hostname = hostname;
            return this;
        }

        /**
         * @param id The compute instance ID to match.
         * 
         * @return builder
         * 
         */
        public Builder id(@Nullable String id) {
            $.id = id;
            return this;
        }

        /**
         * @param tags The instance tags to match (map of key/value).
         * 
         * @return builder
         * 
         */
        public Builder tags(@Nullable Map<String,String> tags) {
            $.tags = tags;
            return this;
        }

        public GetComputePlainArgs build() {
            return $;
        }
    }

}
