// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.exoscale.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumiverse.exoscale.inputs.SKSClusterOidcArgs;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SKSClusterState extends com.pulumi.resources.ResourceArgs {

    public static final SKSClusterState Empty = new SKSClusterState();

    /**
     * @deprecated
     * This attribute has been replaced by `exoscale_ccm`/`metrics_server` attributes, it will be removed in a future release.
     * 
     */
    @Deprecated /* This attribute has been replaced by `exoscale_ccm`/`metrics_server` attributes, it will be removed in a future release. */
    @Import(name="addons")
    private @Nullable Output<List<String>> addons;

    /**
     * @deprecated
     * This attribute has been replaced by `exoscale_ccm`/`metrics_server` attributes, it will be removed in a future release.
     * 
     */
    @Deprecated /* This attribute has been replaced by `exoscale_ccm`/`metrics_server` attributes, it will be removed in a future release. */
    public Optional<Output<List<String>>> addons() {
        return Optional.ofNullable(this.addons);
    }

    /**
     * The CA certificate (in PEM format) for TLS communications between the control plane and the aggregation layer (e.g. `metrics-server`).
     * 
     */
    @Import(name="aggregationCa")
    private @Nullable Output<String> aggregationCa;

    /**
     * @return The CA certificate (in PEM format) for TLS communications between the control plane and the aggregation layer (e.g. `metrics-server`).
     * 
     */
    public Optional<Output<String>> aggregationCa() {
        return Optional.ofNullable(this.aggregationCa);
    }

    /**
     * Enable automatic upgrading of the control plane version (boolean; default: `false`).
     * 
     */
    @Import(name="autoUpgrade")
    private @Nullable Output<Boolean> autoUpgrade;

    /**
     * @return Enable automatic upgrading of the control plane version (boolean; default: `false`).
     * 
     */
    public Optional<Output<Boolean>> autoUpgrade() {
        return Optional.ofNullable(this.autoUpgrade);
    }

    @Import(name="cni")
    private @Nullable Output<String> cni;

    public Optional<Output<String>> cni() {
        return Optional.ofNullable(this.cni);
    }

    /**
     * The CA certificate (in PEM format) for TLS communications between control plane components.
     * 
     */
    @Import(name="controlPlaneCa")
    private @Nullable Output<String> controlPlaneCa;

    /**
     * @return The CA certificate (in PEM format) for TLS communications between control plane components.
     * 
     */
    public Optional<Output<String>> controlPlaneCa() {
        return Optional.ofNullable(this.controlPlaneCa);
    }

    /**
     * The cluster creation date.
     * 
     */
    @Import(name="createdAt")
    private @Nullable Output<String> createdAt;

    /**
     * @return The cluster creation date.
     * 
     */
    public Optional<Output<String>> createdAt() {
        return Optional.ofNullable(this.createdAt);
    }

    /**
     * A free-form text describing the cluster.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return A free-form text describing the cluster.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The cluster API endpoint.
     * 
     */
    @Import(name="endpoint")
    private @Nullable Output<String> endpoint;

    /**
     * @return The cluster API endpoint.
     * 
     */
    public Optional<Output<String>> endpoint() {
        return Optional.ofNullable(this.endpoint);
    }

    /**
     * Deploy the Exoscale [Cloud Controller Manager][ccm] in the control plane (boolean; default: `true`; may only be set at creation time).
     * 
     */
    @Import(name="exoscaleCcm")
    private @Nullable Output<Boolean> exoscaleCcm;

    /**
     * @return Deploy the Exoscale [Cloud Controller Manager][ccm] in the control plane (boolean; default: `true`; may only be set at creation time).
     * 
     */
    public Optional<Output<Boolean>> exoscaleCcm() {
        return Optional.ofNullable(this.exoscaleCcm);
    }

    /**
     * The CA certificate (in PEM format) for TLS communications between kubelets and the control plane.
     * 
     */
    @Import(name="kubeletCa")
    private @Nullable Output<String> kubeletCa;

    /**
     * @return The CA certificate (in PEM format) for TLS communications between kubelets and the control plane.
     * 
     */
    public Optional<Output<String>> kubeletCa() {
        return Optional.ofNullable(this.kubeletCa);
    }

    /**
     * A map of key/value labels.
     * 
     */
    @Import(name="labels")
    private @Nullable Output<Map<String,String>> labels;

    /**
     * @return A map of key/value labels.
     * 
     */
    public Optional<Output<Map<String,String>>> labels() {
        return Optional.ofNullable(this.labels);
    }

    /**
     * Deploy the [Kubernetes Metrics Server][ms] in the control plane (boolean; default: `true`; may only be set at creation time).
     * 
     */
    @Import(name="metricsServer")
    private @Nullable Output<Boolean> metricsServer;

    /**
     * @return Deploy the [Kubernetes Metrics Server][ms] in the control plane (boolean; default: `true`; may only be set at creation time).
     * 
     */
    public Optional<Output<Boolean>> metricsServer() {
        return Optional.ofNullable(this.metricsServer);
    }

    /**
     * The SKS cluster name.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The SKS cluster name.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The list of exoscale.SKSNodepool (IDs) attached to the cluster.
     * 
     */
    @Import(name="nodepools")
    private @Nullable Output<List<String>> nodepools;

    /**
     * @return The list of exoscale.SKSNodepool (IDs) attached to the cluster.
     * 
     */
    public Optional<Output<List<String>>> nodepools() {
        return Optional.ofNullable(this.nodepools);
    }

    /**
     * An OpenID Connect configuration to provide to the Kubernetes API server (may only be set at creation time). Structure is documented below.
     * 
     */
    @Import(name="oidc")
    private @Nullable Output<SKSClusterOidcArgs> oidc;

    /**
     * @return An OpenID Connect configuration to provide to the Kubernetes API server (may only be set at creation time). Structure is documented below.
     * 
     */
    public Optional<Output<SKSClusterOidcArgs>> oidc() {
        return Optional.ofNullable(this.oidc);
    }

    /**
     * The service level of the control plane (`pro` or `starter`; default: `pro`; may only be set at creation time).
     * 
     */
    @Import(name="serviceLevel")
    private @Nullable Output<String> serviceLevel;

    /**
     * @return The service level of the control plane (`pro` or `starter`; default: `pro`; may only be set at creation time).
     * 
     */
    public Optional<Output<String>> serviceLevel() {
        return Optional.ofNullable(this.serviceLevel);
    }

    /**
     * The cluster state.
     * 
     */
    @Import(name="state")
    private @Nullable Output<String> state;

    /**
     * @return The cluster state.
     * 
     */
    public Optional<Output<String>> state() {
        return Optional.ofNullable(this.state);
    }

    /**
     * The version of the control plane (default: latest version available from the API; see `exo compute sks versions` for reference; may only be set at creation time).
     * 
     */
    @Import(name="version")
    private @Nullable Output<String> version;

    /**
     * @return The version of the control plane (default: latest version available from the API; see `exo compute sks versions` for reference; may only be set at creation time).
     * 
     */
    public Optional<Output<String>> version() {
        return Optional.ofNullable(this.version);
    }

    /**
     * The Exoscale [Zone][zone] name.
     * 
     */
    @Import(name="zone")
    private @Nullable Output<String> zone;

    /**
     * @return The Exoscale [Zone][zone] name.
     * 
     */
    public Optional<Output<String>> zone() {
        return Optional.ofNullable(this.zone);
    }

    private SKSClusterState() {}

    private SKSClusterState(SKSClusterState $) {
        this.addons = $.addons;
        this.aggregationCa = $.aggregationCa;
        this.autoUpgrade = $.autoUpgrade;
        this.cni = $.cni;
        this.controlPlaneCa = $.controlPlaneCa;
        this.createdAt = $.createdAt;
        this.description = $.description;
        this.endpoint = $.endpoint;
        this.exoscaleCcm = $.exoscaleCcm;
        this.kubeletCa = $.kubeletCa;
        this.labels = $.labels;
        this.metricsServer = $.metricsServer;
        this.name = $.name;
        this.nodepools = $.nodepools;
        this.oidc = $.oidc;
        this.serviceLevel = $.serviceLevel;
        this.state = $.state;
        this.version = $.version;
        this.zone = $.zone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SKSClusterState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SKSClusterState $;

        public Builder() {
            $ = new SKSClusterState();
        }

        public Builder(SKSClusterState defaults) {
            $ = new SKSClusterState(Objects.requireNonNull(defaults));
        }

        /**
         * @return builder
         * 
         * @deprecated
         * This attribute has been replaced by `exoscale_ccm`/`metrics_server` attributes, it will be removed in a future release.
         * 
         */
        @Deprecated /* This attribute has been replaced by `exoscale_ccm`/`metrics_server` attributes, it will be removed in a future release. */
        public Builder addons(@Nullable Output<List<String>> addons) {
            $.addons = addons;
            return this;
        }

        /**
         * @return builder
         * 
         * @deprecated
         * This attribute has been replaced by `exoscale_ccm`/`metrics_server` attributes, it will be removed in a future release.
         * 
         */
        @Deprecated /* This attribute has been replaced by `exoscale_ccm`/`metrics_server` attributes, it will be removed in a future release. */
        public Builder addons(List<String> addons) {
            return addons(Output.of(addons));
        }

        /**
         * @return builder
         * 
         * @deprecated
         * This attribute has been replaced by `exoscale_ccm`/`metrics_server` attributes, it will be removed in a future release.
         * 
         */
        @Deprecated /* This attribute has been replaced by `exoscale_ccm`/`metrics_server` attributes, it will be removed in a future release. */
        public Builder addons(String... addons) {
            return addons(List.of(addons));
        }

        /**
         * @param aggregationCa The CA certificate (in PEM format) for TLS communications between the control plane and the aggregation layer (e.g. `metrics-server`).
         * 
         * @return builder
         * 
         */
        public Builder aggregationCa(@Nullable Output<String> aggregationCa) {
            $.aggregationCa = aggregationCa;
            return this;
        }

        /**
         * @param aggregationCa The CA certificate (in PEM format) for TLS communications between the control plane and the aggregation layer (e.g. `metrics-server`).
         * 
         * @return builder
         * 
         */
        public Builder aggregationCa(String aggregationCa) {
            return aggregationCa(Output.of(aggregationCa));
        }

        /**
         * @param autoUpgrade Enable automatic upgrading of the control plane version (boolean; default: `false`).
         * 
         * @return builder
         * 
         */
        public Builder autoUpgrade(@Nullable Output<Boolean> autoUpgrade) {
            $.autoUpgrade = autoUpgrade;
            return this;
        }

        /**
         * @param autoUpgrade Enable automatic upgrading of the control plane version (boolean; default: `false`).
         * 
         * @return builder
         * 
         */
        public Builder autoUpgrade(Boolean autoUpgrade) {
            return autoUpgrade(Output.of(autoUpgrade));
        }

        public Builder cni(@Nullable Output<String> cni) {
            $.cni = cni;
            return this;
        }

        public Builder cni(String cni) {
            return cni(Output.of(cni));
        }

        /**
         * @param controlPlaneCa The CA certificate (in PEM format) for TLS communications between control plane components.
         * 
         * @return builder
         * 
         */
        public Builder controlPlaneCa(@Nullable Output<String> controlPlaneCa) {
            $.controlPlaneCa = controlPlaneCa;
            return this;
        }

        /**
         * @param controlPlaneCa The CA certificate (in PEM format) for TLS communications between control plane components.
         * 
         * @return builder
         * 
         */
        public Builder controlPlaneCa(String controlPlaneCa) {
            return controlPlaneCa(Output.of(controlPlaneCa));
        }

        /**
         * @param createdAt The cluster creation date.
         * 
         * @return builder
         * 
         */
        public Builder createdAt(@Nullable Output<String> createdAt) {
            $.createdAt = createdAt;
            return this;
        }

        /**
         * @param createdAt The cluster creation date.
         * 
         * @return builder
         * 
         */
        public Builder createdAt(String createdAt) {
            return createdAt(Output.of(createdAt));
        }

        /**
         * @param description A free-form text describing the cluster.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description A free-form text describing the cluster.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param endpoint The cluster API endpoint.
         * 
         * @return builder
         * 
         */
        public Builder endpoint(@Nullable Output<String> endpoint) {
            $.endpoint = endpoint;
            return this;
        }

        /**
         * @param endpoint The cluster API endpoint.
         * 
         * @return builder
         * 
         */
        public Builder endpoint(String endpoint) {
            return endpoint(Output.of(endpoint));
        }

        /**
         * @param exoscaleCcm Deploy the Exoscale [Cloud Controller Manager][ccm] in the control plane (boolean; default: `true`; may only be set at creation time).
         * 
         * @return builder
         * 
         */
        public Builder exoscaleCcm(@Nullable Output<Boolean> exoscaleCcm) {
            $.exoscaleCcm = exoscaleCcm;
            return this;
        }

        /**
         * @param exoscaleCcm Deploy the Exoscale [Cloud Controller Manager][ccm] in the control plane (boolean; default: `true`; may only be set at creation time).
         * 
         * @return builder
         * 
         */
        public Builder exoscaleCcm(Boolean exoscaleCcm) {
            return exoscaleCcm(Output.of(exoscaleCcm));
        }

        /**
         * @param kubeletCa The CA certificate (in PEM format) for TLS communications between kubelets and the control plane.
         * 
         * @return builder
         * 
         */
        public Builder kubeletCa(@Nullable Output<String> kubeletCa) {
            $.kubeletCa = kubeletCa;
            return this;
        }

        /**
         * @param kubeletCa The CA certificate (in PEM format) for TLS communications between kubelets and the control plane.
         * 
         * @return builder
         * 
         */
        public Builder kubeletCa(String kubeletCa) {
            return kubeletCa(Output.of(kubeletCa));
        }

        /**
         * @param labels A map of key/value labels.
         * 
         * @return builder
         * 
         */
        public Builder labels(@Nullable Output<Map<String,String>> labels) {
            $.labels = labels;
            return this;
        }

        /**
         * @param labels A map of key/value labels.
         * 
         * @return builder
         * 
         */
        public Builder labels(Map<String,String> labels) {
            return labels(Output.of(labels));
        }

        /**
         * @param metricsServer Deploy the [Kubernetes Metrics Server][ms] in the control plane (boolean; default: `true`; may only be set at creation time).
         * 
         * @return builder
         * 
         */
        public Builder metricsServer(@Nullable Output<Boolean> metricsServer) {
            $.metricsServer = metricsServer;
            return this;
        }

        /**
         * @param metricsServer Deploy the [Kubernetes Metrics Server][ms] in the control plane (boolean; default: `true`; may only be set at creation time).
         * 
         * @return builder
         * 
         */
        public Builder metricsServer(Boolean metricsServer) {
            return metricsServer(Output.of(metricsServer));
        }

        /**
         * @param name The SKS cluster name.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The SKS cluster name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param nodepools The list of exoscale.SKSNodepool (IDs) attached to the cluster.
         * 
         * @return builder
         * 
         */
        public Builder nodepools(@Nullable Output<List<String>> nodepools) {
            $.nodepools = nodepools;
            return this;
        }

        /**
         * @param nodepools The list of exoscale.SKSNodepool (IDs) attached to the cluster.
         * 
         * @return builder
         * 
         */
        public Builder nodepools(List<String> nodepools) {
            return nodepools(Output.of(nodepools));
        }

        /**
         * @param nodepools The list of exoscale.SKSNodepool (IDs) attached to the cluster.
         * 
         * @return builder
         * 
         */
        public Builder nodepools(String... nodepools) {
            return nodepools(List.of(nodepools));
        }

        /**
         * @param oidc An OpenID Connect configuration to provide to the Kubernetes API server (may only be set at creation time). Structure is documented below.
         * 
         * @return builder
         * 
         */
        public Builder oidc(@Nullable Output<SKSClusterOidcArgs> oidc) {
            $.oidc = oidc;
            return this;
        }

        /**
         * @param oidc An OpenID Connect configuration to provide to the Kubernetes API server (may only be set at creation time). Structure is documented below.
         * 
         * @return builder
         * 
         */
        public Builder oidc(SKSClusterOidcArgs oidc) {
            return oidc(Output.of(oidc));
        }

        /**
         * @param serviceLevel The service level of the control plane (`pro` or `starter`; default: `pro`; may only be set at creation time).
         * 
         * @return builder
         * 
         */
        public Builder serviceLevel(@Nullable Output<String> serviceLevel) {
            $.serviceLevel = serviceLevel;
            return this;
        }

        /**
         * @param serviceLevel The service level of the control plane (`pro` or `starter`; default: `pro`; may only be set at creation time).
         * 
         * @return builder
         * 
         */
        public Builder serviceLevel(String serviceLevel) {
            return serviceLevel(Output.of(serviceLevel));
        }

        /**
         * @param state The cluster state.
         * 
         * @return builder
         * 
         */
        public Builder state(@Nullable Output<String> state) {
            $.state = state;
            return this;
        }

        /**
         * @param state The cluster state.
         * 
         * @return builder
         * 
         */
        public Builder state(String state) {
            return state(Output.of(state));
        }

        /**
         * @param version The version of the control plane (default: latest version available from the API; see `exo compute sks versions` for reference; may only be set at creation time).
         * 
         * @return builder
         * 
         */
        public Builder version(@Nullable Output<String> version) {
            $.version = version;
            return this;
        }

        /**
         * @param version The version of the control plane (default: latest version available from the API; see `exo compute sks versions` for reference; may only be set at creation time).
         * 
         * @return builder
         * 
         */
        public Builder version(String version) {
            return version(Output.of(version));
        }

        /**
         * @param zone The Exoscale [Zone][zone] name.
         * 
         * @return builder
         * 
         */
        public Builder zone(@Nullable Output<String> zone) {
            $.zone = zone;
            return this;
        }

        /**
         * @param zone The Exoscale [Zone][zone] name.
         * 
         * @return builder
         * 
         */
        public Builder zone(String zone) {
            return zone(Output.of(zone));
        }

        public SKSClusterState build() {
            return $;
        }
    }

}
